import { expect, test } from '@playwright/test';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const samples=[
  {slug:'restaurant-offer',type:'offer',layout:'offer',name:'Saffron Table',category:'Restaurant',headline:'A Feast Worth Sharing',eyebrow:'WEEKEND TABLE SPECIAL',support:'Gather your favourite people for handcrafted Indian flavours.',offer:'20% OFF FAMILY DINING',cta:'Reserve Your Table',location:'Baner, Pune',address:'Ground Floor, West Avenue, Baner Road, Pune, Maharashtra 411045',phone:'+91 98765 12000',website:'saffrontable.in',colors:['#180b07','#8f2f12','#ffb45c']},
  {slug:'salon-product',type:'product_service',layout:'product',name:'Aurelia Salon',category:'Salon & Beauty',headline:'Your Weekend Look Starts Here',eyebrow:'SIGNATURE BEAUTY EDIT',support:'Refresh your style with our most-loved hair and beauty rituals.',offer:'',cta:'Book Your Appointment',location:'Bibwewadi, Pune',address:'Aurelia House, Near City Pride, Bibwewadi Main Road, Pune, Maharashtra 411037',phone:'+91 98220 44881',website:'@aureliasalon',colors:['#190d19','#7b285f','#f6a7cf']},
  {slug:'gym-announcement',type:'announcement',layout:'announcement',name:'Forge Fitness Club',category:'Gym & Fitness',headline:'Our New Strength Floor Is Open',eyebrow:'BIG CLUB UPDATE',support:'More space, new equipment and coaching built for your strongest season.',offer:'',cta:'Start Your Trial',location:'Indiranagar, Bengaluru',address:'12th Main Road, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560038',phone:'+91 99001 88442',website:'forgefit.club',colors:['#090d14','#1f4650','#b8f23d']},
  {slug:'clinic-daily',type:'today',layout:'daily',name:'Niramaya Family Clinic',category:'Medical Clinic',headline:'Care That Makes Time For You',eyebrow:'FRIDAY HEALTH NOTE',support:'Thoughtful consultations for every stage of your family’s wellbeing.',offer:'',cta:'Book A Consultation',location:'Kothrud, Pune',address:'Second Floor, Shantiban Commercial Centre, Paud Road, Kothrud, Pune, Maharashtra 411038',phone:'+91 97655 30110',website:'niramayaclinic.in',colors:['#071918','#21665f','#82ded1']},
  {slug:'retail-festival',type:'festival',layout:'festival',name:'Mitti & Loom',category:'Retail Boutique',headline:'Celebrate New Beginnings In Style',eyebrow:'FESTIVE COLLECTION',support:'Thoughtful Indian craft, contemporary silhouettes and gifts made memorable.',offer:'',cta:'Visit The Collection',location:'C Scheme, Jaipur',address:'27 Prithviraj Road, C Scheme, Jaipur, Rajasthan 302001',phone:'+91 93511 77220',website:'@mittiandloom',colors:['#171027','#5941a9','#f3a34b']},
  {slug:'local-service-marathi',type:'today',layout:'daily',name:'सह्याद्री होम सर्व्हिसेस',category:'Local Home Services',headline:'घराची काळजी, आता निश्चिंत',eyebrow:'आजची खास सेवा',support:'विश्वासार्ह दुरुस्ती आणि देखभाल सेवा तुमच्या परिसरात.',offer:'',cta:'आजच संपर्क करा',location:'कोथरूड, पुणे',address:'पौड रोड, कोथरूड, पुणे, महाराष्ट्र ४११०३८',phone:'+91 98900 11442',website:'',colors:['#061510','#146340','#6be3a5']},
] as const;

test('export six realistic 1080x1080 professional layout samples',async({page})=>{test.setTimeout(60_000);await page.goto('/',{waitUntil:'domcontentloaded'});const output=join(process.cwd(),'test-results','poster-samples');mkdirSync(output,{recursive:true});for(const[index,sample]of samples.entries()){const dataUrl=await page.evaluate(async({sample,index})=>{const{renderPoster}=await import('/src/features/ai-content/posterRenderer.ts');const generation={id:`quality-${index}`,businessId:`business-${index}`,type:sample.type,prompt:`Create ${sample.slug}`,caption:`${sample.headline}\n${sample.support}`,headline:sample.headline,supportingText:sample.support,cta:sample.cta,creative:{kind:'gradient' as const,colors:[...sample.colors] as[string,string,string],mood:'premium',composition:sample.layout,decorativeStyle:'controlled',layout:sample.layout,variant:index},renderer:{businessName:sample.name,logoUrl:'',heroImageUrl:'',category:sample.category,headline:sample.headline,eyebrow:sample.eyebrow,supportingText:sample.support,cta:sample.cta,offer:sample.offer,address:sample.address,location:sample.location,phone:sample.phone,whatsapp:sample.phone,website:sample.website,instagram:'',dateLabel:'Friday, 14 August 2026'},generationDate:'2026-08-14',createdAt:'2026-08-14T10:00:00Z',metadata:{}};const canvas=await renderPoster(generation);if(canvas.width!==1080||canvas.height!==1080)throw new Error('Unexpected poster dimensions');return canvas.toDataURL('image/png');},{sample,index});const bytes=Buffer.from(dataUrl.split(',')[1],'base64');expect(bytes.subarray(1,4).toString()).toBe('PNG');writeFileSync(join(output,`${sample.slug}.png`),bytes);}});
