import type { Business } from '@/types';
import { dataMode, requireSupabase } from '@/lib/supabase';

export type AIContentType='today'|'offer'|'festival'|'product_service'|'announcement'|'custom';
export type PosterLayout='offer'|'product'|'festival'|'daily'|'announcement';
export interface CreativeSpec{kind:'gradient'|'image';backgroundUrl?:string;colors:[string,string,string];mood:string;composition:string;decorativeStyle:string;layout?:PosterLayout;variant?:number}
export interface RendererData{businessName:string;logoUrl:string;heroImageUrl?:string;category?:string;headline:string;eyebrow?:string;supportingText:string;cta:string;offer:string;address:string;location:string;phone:string;whatsapp:string;website:string;instagram?:string;dateLabel:string}
export interface AIContentGeneration{id:string;businessId:string;type:AIContentType;prompt:string;caption:string;headline:string;supportingText:string;cta:string;creative:CreativeSpec;renderer:RendererData;posterPath?:string;posterUrl?:string;generationDate:string;createdAt:string;metadata:Record<string,unknown>}

export const AI_CONTENT_TEST_DAILY_LIMIT=5;

type Row=Record<string,unknown>;
const row=(value:unknown):Row=>value&&typeof value==='object'?value as Row:{};
const str=(value:unknown)=>typeof value==='string'?value:'';
function mapGeneration(value:unknown):AIContentGeneration{const r=row(value);return{id:str(r.id),businessId:str(r.business_id),type:str(r.generation_type) as AIContentType,prompt:str(r.prompt),caption:str(r.caption),headline:str(r.headline),supportingText:str(r.supporting_text),cta:str(r.cta),creative:row(r.creative_spec) as unknown as CreativeSpec,renderer:row(r.renderer_data) as unknown as RendererData,posterPath:str(r.poster_path)||undefined,generationDate:str(r.generation_date),createdAt:str(r.created_at),metadata:row(r.metadata)};}
function indiaDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(new Date());}
function mockKey(businessId:string){return `founder-ai-content:${businessId}`;}
function mockHistory(businessId:string):AIContentGeneration[]{try{return JSON.parse(localStorage.getItem(mockKey(businessId))||'[]') as AIContentGeneration[];}catch{return[];}}
const layouts:Record<AIContentType,PosterLayout>={today:'daily',offer:'offer',festival:'festival',product_service:'product',announcement:'announcement',custom:'product'};
const categoryPalettes:Record<string,[string,string,string]>={food:['#180b07','#8f2f12','#ffb45c'],beauty:['#190d19','#7b285f','#f6a7cf'],fitness:['#090d14','#1f4650','#b8f23d'],tech:['#07121f','#174b76','#4fd1ff'],medical:['#071918','#21665f','#82ded1'],retail:['#171027','#5941a9','#f3a34b'],default:['#061510','#146340','#6be3a5']};
function categoryGroup(category:string){const value=category.toLowerCase();if(/restaurant|cafe|food|bakery/.test(value))return'food';if(/salon|beauty|spa|fashion/.test(value))return'beauty';if(/gym|fitness|sport/.test(value))return'fitness';if(/tech|software|electronic/.test(value))return'tech';if(/medical|clinic|doctor|dental|professional/.test(value))return'medical';if(/retail|store|shop|boutique/.test(value))return'retail';return'default';}
function mockGenerate(prompt:string,type:AIContentType,business:Business,index:number):AIContentGeneration{const date=new Date(),dateLabel=new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(date);const weekday=new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',weekday:'long'}).format(date),service=business.servicesSummary||business.description||business.category,offer=business.todayOffer||'';const daily=[`Make ${weekday} Remarkable`,`A Better ${weekday} Starts Here`,`Your Local ${weekday} Favourite`],headlines:Record<AIContentType,string[]>={today:daily,offer:['More Value. More Reasons To Visit.','Your Favourite Deal Is Here','A Little Extra, Just For You'],festival:['Celebrate The Moment Together','Warm Wishes. Beautiful Beginnings.','Joy Looks Better Together'],product_service:['Made To Be Your New Favourite','Thoughtfully Made For You','Discover What We Do Best'],announcement:['Something New Is Here','A Fresh Chapter Begins','Good News, Right This Way'],custom:['Your Idea, Brought To Life','Made Around What Matters','A Better Choice Starts Here']};const headline=headlines[type][index%headlines[type].length],supportingText=(type==='offer'&&offer?offer:service).replace(/\s+/g,' ').trim().slice(0,150),cta=business.whatsapp?'Message us on WhatsApp':business.phone?'Call us today':'Visit us today',eyebrows:Record<AIContentType,string>={today:`${weekday.toUpperCase()} EDIT`,offer:'LIMITED-TIME OFFER',festival:'CELEBRATE WITH US',product_service:'FEATURED FOR YOU',announcement:'BUSINESS UPDATE',custom:'CREATED FOR YOU'},group=categoryGroup(business.category),colors=categoryPalettes[group];return{id:crypto.randomUUID(),businessId:business.id,type,prompt,caption:`${eyebrows[type]}\n\n${headline}\n${supportingText}\n\n${cta}.${business.city||business.location?` Find us in ${business.city||business.location}.`:''}`,headline,supportingText,cta,creative:{kind:'gradient',colors,mood:`premium ${group} campaign`,composition:layouts[type],decorativeStyle:`category-aware ${group} geometry`,layout:layouts[type],variant:index%4},renderer:{businessName:business.name,logoUrl:business.logoUrl,heroImageUrl:business.coverUrl||business.galleryImages[0]||'',category:business.category,headline,eyebrow:eyebrows[type],supportingText,cta,offer,address:business.address,location:business.city||business.location,phone:business.phone,whatsapp:business.whatsapp,website:business.socialLinks.website||'',instagram:business.socialLinks.instagram||'',dateLabel},generationDate:indiaDate(),createdAt:date.toISOString(),metadata:{textProvider:'mock-local',creativeProvider:'mock-premium',layout:layouts[type],categoryGroup:group,variant:index%4}};}

export const AIContentService={
  async history(businessId:string){
    if(dataMode==='mock')return mockHistory(businessId);
    const client=requireSupabase();const{data,error}=await client.from('ai_content_generations').select('*').eq('business_id',businessId).eq('status','completed').order('created_at',{ascending:false}).limit(30);if(error)throw error;
    const items=(data??[]).map(mapGeneration);await Promise.all(items.map(async(item)=>{if(!item.posterPath)return;const{data:signed}=await client.storage.from('ai-content-posters').createSignedUrl(item.posterPath,3600);item.posterUrl=signed?.signedUrl;}));return items;
  },
  async generate(input:{prompt:string;type:AIContentType;business:Business;requestId:string}){
    const prompt=[...input.prompt].map(character=>{const code=character.charCodeAt(0);return code<32||code===127?' ':character;}).join('').replace(/\s+/g,' ').trim();if(!prompt||prompt.length>600)throw new Error('Keep your prompt between 1 and 600 characters.');
    if(dataMode==='mock'){const previous=mockHistory(input.business.id),used=this.usedCountToday(previous);if(used>=AI_CONTENT_TEST_DAILY_LIMIT)throw new Error("You've used today's 5 free creations.");const generated=mockGenerate(prompt,input.type,input.business,used);localStorage.setItem(mockKey(input.business.id),JSON.stringify([generated,...previous]));return generated;}
    const{data,error}=await requireSupabase().functions.invoke<{generation:unknown}>('ai-content-studio',{body:{prompt,generationType:input.type,requestId:input.requestId}});
    if(error){let message=error.message||'Generation failed';try{const payload=await (error as {context?:Response}).context?.json() as {error?:string}|undefined;if(payload?.error)message=payload.error;}catch{/* use safe fallback */}throw new Error(message);}
    return mapGeneration(data?.generation);
  },
  async attachPoster(generation:AIContentGeneration,blob:Blob){
    if(dataMode==='mock')return generation;
    const client=requireSupabase(),path=`business/${generation.businessId}/${generation.id}.png`;const{error:uploadError}=await client.storage.from('ai-content-posters').upload(path,blob,{contentType:'image/png',upsert:true});if(uploadError)throw uploadError;const{error}=await client.rpc('attach_ai_content_poster',{target_generation_id:generation.id,target_poster_path:path});if(error)throw error;return{...generation,posterPath:path};
  },
  async dailyLimit(businessId:string){if(dataMode==='mock')return AI_CONTENT_TEST_DAILY_LIMIT;const{data,error}=await requireSupabase().rpc('ai_content_daily_limit',{target_business_id:businessId});if(error)throw error;return typeof data==='number'?data:AI_CONTENT_TEST_DAILY_LIMIT;},
  usedCountToday(items:AIContentGeneration[],today=indiaDate()){return items.filter(item=>item.generationDate===today).length;},
  remainingToday(items:AIContentGeneration[],limit:number,today=indiaDate()){return Math.max(0,limit-this.usedCountToday(items,today));},
};
