/* eslint-disable @typescript-eslint/no-unused-vars -- adapter signatures intentionally preserve the existing frontend contracts */
import type {
  AnalyticsMetric, AnalyticsSeries, Business, BusinessFollower, BusinessTemplateConfig, Category, Comment, Conversation,
  Deal, DealClaim, LoyaltyProgram, Message, Notification, OpeningHours, Payment, Post, QRScan, Referral, Report, Review,
  Reward, ScratchCampaign, ScratchResult, Story, StoryHighlight, Subscription, TemplateId, TrafficSource, VideoClip,
  CustomerAccount, BusinessOwner, RedemptionState,
} from '@/types';
import { requireSupabase } from '@/lib/supabase';
import { staticCategories } from '@/data/categories';

export interface BusinessAssets { logo?: File; cover?: File; gallery?: File[] }
export interface PostCreateInput { type: Post['type']; caption: string; location?: string; ctaLabel?: string; ctaLink?: string }
export interface StoryCreateInput { storyType: string; caption?: string }
export interface DealCreateInput { title: string; description: string; originalPrice: number; offerPrice: number; discount: number; startsAt: string; endsAt: string; maxClaims?: number; terms?: string; ctaLabel?: string }
export interface ClipCreateInput { caption: string; dealId?: string; music?: string }

type Row = Record<string, unknown>;
const row = (value: unknown): Row => value && typeof value === 'object' ? value as Row : {};
const rows = (value: unknown): Row[] => Array.isArray(value) ? value.map(row) : [];
const str = (value: unknown, fallback = '') => typeof value === 'string' ? value : fallback;
const num = (value: unknown, fallback = 0) => typeof value === 'number' ? value : Number(value) || fallback;
const bool = (value: unknown) => Boolean(value);
const iso = (value: unknown) => str(value, new Date().toISOString());

function fail(error: { message: string } | null) { if (error) throw new Error(error.message); }
async function userId() { const { data, error } = await requireSupabase().auth.getUser(); fail(error); if (!data.user) throw new Error('Authentication required.'); return data.user.id; }
function publicAsset(bucket: string, path: unknown) { const value = str(path); if (!value || /^https?:\/\//.test(value)) return value; return requireSupabase().storage.from(bucket).getPublicUrl(value).data.publicUrl; }

const uploadRules: Record<string, { types: string[]; maxBytes: number }> = {
  'business-logos': { types: ['image/jpeg','image/png','image/webp'], maxBytes: 5 * 1024 * 1024 },
  'business-covers': { types: ['image/jpeg','image/png','image/webp'], maxBytes: 10 * 1024 * 1024 },
  'business-gallery': { types: ['image/jpeg','image/png','image/webp'], maxBytes: 10 * 1024 * 1024 },
  'post-media': { types: ['image/jpeg','image/png','image/webp','video/mp4','video/webm'], maxBytes: 50 * 1024 * 1024 },
  'story-media': { types: ['image/jpeg','image/png','image/webp','video/mp4','video/webm'], maxBytes: 50 * 1024 * 1024 },
  'deal-media': { types: ['image/jpeg','image/png','image/webp','video/mp4','video/webm'], maxBytes: 50 * 1024 * 1024 },
  'message-media': { types: ['image/jpeg','image/png','image/webp'], maxBytes: 20 * 1024 * 1024 },
};
function extension(file: File) { const value = file.name.split('.').pop()?.toLowerCase().replace(/[^a-z0-9]/g,''); return value || (file.type.startsWith('video/') ? 'mp4' : 'bin'); }
function validateUpload(bucket: string, file: File) { const rule=uploadRules[bucket]; if(!rule)throw new Error('Unsupported upload destination.'); if(!rule.types.includes(file.type))throw new Error(`Unsupported file type for ${bucket}.`); if(file.size<=0||file.size>rule.maxBytes)throw new Error(`File must be smaller than ${Math.round(rule.maxBytes/1024/1024)} MB.`); }
async function uploadBusinessAsset(bucket: string, businessId: string, file: File) { validateUpload(bucket,file); const path=`business/${businessId}/${crypto.randomUUID()}.${extension(file)}`; const{error}=await requireSupabase().storage.from(bucket).upload(path,file,{contentType:file.type,upsert:false});fail(error);return path; }
async function uploadUserAsset(bucket: string, userId: string, file: File) { validateUpload(bucket,file); const path=`user/${userId}/${crypto.randomUUID()}.${extension(file)}`; const{error}=await requireSupabase().storage.from(bucket).upload(path,file,{contentType:file.type,upsert:false});fail(error);return path; }
async function removeAsset(bucket:string,path:string){if(path)await requireSupabase().storage.from(bucket).remove([path]);}

function businessPayload(updates: Partial<Business>): Row {
  const payload: Row = {};
  const mapping: Partial<Record<keyof Business, string>> = { name:'name',username:'username',description:'description',bio:'bio',category:'category',phone:'phone',whatsapp:'whatsapp',email:'email',address:'address',location:'location',city:'city',state:'state',templateId:'template_key',templateTheme:'theme',todayOffer:'today_offer',servicesSummary:'services_summary',preferredContentLanguage:'preferred_content_language' };
  for (const [key,column] of Object.entries(mapping)) { const value=updates[key as keyof Business]; if(value!==undefined)payload[column]=value; }
  if(updates.openingHours)payload.opening_hours=updates.openingHours;
  if(updates.featuredProducts)payload.featured_products=updates.featuredProducts;
  if(updates.popularItems)payload.popular_items=updates.popularItems;
  if(updates.socialLinks){if(updates.socialLinks.instagram!==undefined)payload.instagram_url=updates.socialLinks.instagram;if(updates.socialLinks.website!==undefined)payload.website_url=updates.socialLinks.website;}
  return payload;
}

function mapBusiness(value: unknown): Business {
  const r = row(value); const lifecycle = str(r.lifecycle); const subscription = str(r.subscription_status);
  return {
    id: str(r.id), ownerId: str(r.owner_id), name: str(r.name), username: str(r.username), logoUrl: publicAsset('business-logos', r.logo_url),
    coverUrl: publicAsset('business-covers', r.cover_url), category: str(r.category), categoryIcon: str(r.category_icon, 'Store'),
    description: str(r.description), bio: str(r.bio), location: str(r.location, [str(r.city), str(r.state)].filter(Boolean).join(', ')),
    city: str(r.city), state: str(r.state), phone: str(r.phone), whatsapp: str(r.whatsapp), email: str(r.email), address: str(r.address),
    latitude: r.latitude == null ? undefined : num(r.latitude), longitude: r.longitude == null ? undefined : num(r.longitude),
    openingHours: (Array.isArray(r.opening_hours) ? r.opening_hours : []) as OpeningHours[],
    socialLinks: { instagram: str(r.instagram_url), website: str(r.website_url), whatsapp: str(r.whatsapp) },
    templateId: str(r.template_key, 'minimal_premium') as TemplateId, templateTheme: (['light','dark'].includes(str(r.theme)) ? str(r.theme) : 'default') as Business['templateTheme'],
    isVerified: bool(r.is_verified), isOpenNow: bool(r.is_open_now), rating: num(r.rating), reviewCount: num(r.review_count), followerCount: num(r.follower_count),
    qrCode: str(r.qr_code), shortUrl: str(r.short_url, r.qr_code ? `founder.env/q/${r.qr_code}` : ''), plan: subscription === 'active' ? 'pro' : 'lite',
    status: lifecycle === 'suspended' ? 'suspended' : lifecycle === 'draft' || lifecycle === 'pending_activation' ? 'pending' : 'active', joinedAt: iso(r.created_at),
    galleryImages: rows(r.gallery).map((item) => publicAsset('business-gallery', item.storage_path)),
    featuredProducts: (Array.isArray(r.featured_products) ? r.featured_products : []) as Business['featuredProducts'],
    popularItems: (Array.isArray(r.popular_items) ? r.popular_items : []) as Business['popularItems'], todayOffer: str(r.today_offer) || undefined,
    servicesSummary: str(r.services_summary), preferredContentLanguage: str(r.preferred_content_language,'Auto') as Business['preferredContentLanguage'],
  };
}

async function businessQuery() {
  const client = requireSupabase();
  const { data, error } = await client.from('business_public').select('*, gallery:business_gallery(storage_path,sort_order)'); fail(error);
  return rows(data).map(mapBusiness);
}

export const supabaseBusinessService = {
  getAll: businessQuery,
  async getByUsername(username: string) { const all = await businessQuery(); return all.find((item) => item.username.toLowerCase() === username.toLowerCase()) ?? null; },
  async getById(id: string) { const all = await businessQuery(); return all.find((item) => item.id === id) ?? null; },
  async getByCategory(category: string) { return (await businessQuery()).filter((item) => category === 'all' || item.category.toLowerCase() === category.toLowerCase()); },
  async getFeatured() { return (await businessQuery()).filter((item) => item.isVerified).slice(0, 4); },
  async getTrending() { return (await businessQuery()).sort((a, b) => b.followerCount - a.followerCount); },
  async getTopRated() { return (await businessQuery()).sort((a, b) => b.rating - a.rating); },
  async getNew() { return (await businessQuery()).sort((a, b) => Date.parse(b.joinedAt) - Date.parse(a.joinedAt)); },
  async search(query: string) { const q = query.toLowerCase(); return (await businessQuery()).filter((item) => `${item.name} ${item.username} ${item.category} ${item.city}`.toLowerCase().includes(q)); },
  async getByOwner(ownerId: string) { const client = requireSupabase(); const { data, error } = await client.from('businesses').select('*, gallery:business_gallery(storage_path,sort_order)').eq('owner_id', ownerId); fail(error); return rows(data).map(mapBusiness); },
  async create(input: Partial<Business>, assets: BusinessAssets = {}) {
    const uid=await userId(); const payload=businessPayload(input); payload.owner_id=uid;
    const{data,error}=await requireSupabase().from('businesses').insert(payload).select('*').single();fail(error);if(!data)throw new Error('Business creation failed.');
    const businessId=str(data.id); const uploaded:{bucket:string;path:string}[]=[];
    try{
      if(assets.logo){const path=await uploadBusinessAsset('business-logos',businessId,assets.logo);uploaded.push({bucket:'business-logos',path});payload.logo_url=path;}
      if(assets.cover){const path=await uploadBusinessAsset('business-covers',businessId,assets.cover);uploaded.push({bucket:'business-covers',path});payload.cover_url=path;}
      if(assets.gallery?.length){for(const[index,file]of assets.gallery.entries()){const path=await uploadBusinessAsset('business-gallery',businessId,file);uploaded.push({bucket:'business-gallery',path});const result=await requireSupabase().from('business_gallery').insert({business_id:businessId,storage_path:path,sort_order:index});fail(result.error);}}
      if(uploaded.length){const result=await requireSupabase().from('businesses').update({logo_url:payload.logo_url,cover_url:payload.cover_url}).eq('id',businessId).select('*').single();fail(result.error);return mapBusiness(result.data);}
      return mapBusiness(data);
    }catch(error){await Promise.allSettled(uploaded.map((item)=>removeAsset(item.bucket,item.path)));await requireSupabase().from('businesses').delete().eq('id',businessId);throw error;}
  },
  async update(id: string, updates: Partial<Business>, assets: BusinessAssets = {}) {
    const payload=businessPayload(updates); const uploaded:{bucket:string;path:string}[]=[];
    try{
      if(assets.logo){const path=await uploadBusinessAsset('business-logos',id,assets.logo);uploaded.push({bucket:'business-logos',path});payload.logo_url=path;}
      if(assets.cover){const path=await uploadBusinessAsset('business-covers',id,assets.cover);uploaded.push({bucket:'business-covers',path});payload.cover_url=path;}
      if(assets.gallery?.length){for(const[index,file]of assets.gallery.entries()){const path=await uploadBusinessAsset('business-gallery',id,file);uploaded.push({bucket:'business-gallery',path});const result=await requireSupabase().from('business_gallery').insert({business_id:id,storage_path:path,sort_order:index});fail(result.error);}}
      const { data, error } = await requireSupabase().from('businesses').update(payload).eq('id', id).select('*').single(); fail(error); return data ? mapBusiness(data) : null;
    }catch(error){await Promise.allSettled(uploaded.map((item)=>removeAsset(item.bucket,item.path)));throw error;}
  },
};

function mapPost(value: unknown, state: { liked?: Set<string>; saved?: Set<string>; reposted?: Set<string>; following?: Set<string>; likes?: Map<string,number>; comments?: Map<string,number> } = {}): Post {
  const r = row(value); const business = row(r.businesses); const media = rows(r.post_media).sort((a,b) => num(a.sort_order)-num(b.sort_order)); const id = str(r.id);
  return { id, businessId:str(r.business_id), businessName:str(business.name), businessUsername:str(business.username), businessAvatar:publicAsset('business-logos',business.logo_url), businessCategory:str(business.category), businessLocation:str(business.location), type:str(r.type,'standard') as Post['type'],
    media:media.map((item) => ({ id:str(item.id), type:str(item.media_type,'image') as 'image'|'video', url:publicAsset('post-media',item.storage_path), thumbnailUrl:publicAsset('post-media',item.thumbnail_path) || undefined })), caption:str(r.caption), location:str(r.location)||undefined, ctaLabel:str(r.cta_label)||undefined, ctaLink:str(r.cta_url)||undefined,
    likeCount:state.likes?.get(id) ?? 0, commentCount:state.comments?.get(id) ?? 0, shareCount:0, repostCount:0, saveCount:0,
    isLiked:state.liked?.has(id) ?? false, isSaved:state.saved?.has(id) ?? false, isReposted:state.reposted?.has(id) ?? false, isFollowing:state.following?.has(str(r.business_id)) ?? false, createdAt:iso(r.created_at) };
}

async function loadPosts(): Promise<Post[]> {
  const client = requireSupabase(); const { data, error } = await client.from('posts').select('*, businesses(name,username,logo_url,category,location), post_media(*)').eq('status','published').order('created_at',{ascending:false}); fail(error);
  const base = rows(data); const ids = base.map((item) => str(item.id)); if (!ids.length) return [];
  const [likesResult, commentsResult, authResult] = await Promise.all([client.from('post_likes').select('post_id,customer_id').in('post_id',ids), client.from('post_comments_public').select('post_id').in('post_id',ids), client.auth.getSession()]);
  const current = authResult.data.session?.user.id; const liked = new Set(rows(likesResult.data).filter((item) => item.customer_id === current).map((item) => str(item.post_id)));
  const likes = countBy(rows(likesResult.data),'post_id'); const comments = countBy(rows(commentsResult.data),'post_id'); let saved = new Set<string>(); let reposted = new Set<string>(); let following = new Set<string>();
  if (current) { const [savedResult,repostResult,followingResult] = await Promise.all([client.from('saved_posts').select('post_id').eq('customer_id',current).in('post_id',ids),client.from('reposts').select('post_id').eq('customer_id',current).in('post_id',ids),client.from('business_followers').select('business_id').eq('customer_id',current)]); saved = new Set(rows(savedResult.data).map((item)=>str(item.post_id))); reposted = new Set(rows(repostResult.data).map((item)=>str(item.post_id))); following = new Set(rows(followingResult.data).map((item)=>str(item.business_id))); }
  return base.map((item) => mapPost(item,{liked,saved,reposted,following,likes,comments}));
}
function countBy(items: Row[], key: string) { const result = new Map<string,number>(); for (const item of items) { const id=str(item[key]); result.set(id,(result.get(id)??0)+1); } return result; }
async function toggleOwn(table: 'post_likes'|'saved_posts'|'reposts'|'saved_deals'|'deal_clip_likes'|'saved_deal_clips'|'review_helpful', entityColumn: string, entityId: string) { const client=requireSupabase(); const uid=await userId(); const {data,error}=await client.from(table).select(entityColumn).eq(entityColumn,entityId).eq('customer_id',uid).maybeSingle(); fail(error); if(data){ const result=await client.from(table).delete().eq(entityColumn,entityId).eq('customer_id',uid); fail(result.error); } else { const result=await client.from(table).insert({[entityColumn]:entityId,customer_id:uid}); fail(result.error); } }

export const supabasePostService = {
  getFeed: () => loadPosts(),
  async create(businessId:string,input:PostCreateInput,file?:File){if(!file)throw new Error('Post media is required.');let path='';let postId='';try{path=await uploadBusinessAsset('post-media',businessId,file);const{data,error}=await requireSupabase().from('posts').insert({business_id:businessId,type:input.type,caption:input.caption,status:'published',location:input.location||null,cta_label:input.ctaLabel||null,cta_url:input.ctaLink||null}).select('id').single();fail(error);postId=str(data?.id);const result=await requireSupabase().from('post_media').insert({post_id:postId,storage_path:path,media_type:file.type.startsWith('video/')?'video':'image',sort_order:0});fail(result.error);return postId;}catch(error){if(postId)await requireSupabase().from('posts').delete().eq('id',postId);await removeAsset('post-media',path);throw error;}},
  async getByBusiness(businessId:string){ return (await loadPosts()).filter((item)=>item.businessId===businessId); },
  async getById(id:string){ return (await loadPosts()).find((item)=>item.id===id)??null; },
  async toggleLike(id:string){ await toggleOwn('post_likes','post_id',id); return this.getById(id); },
  async toggleSave(id:string){ await toggleOwn('saved_posts','post_id',id); return this.getById(id); },
  async toggleRepost(id:string){ await toggleOwn('reposts','post_id',id); return this.getById(id); },
  async getComments(postId:string){ const client=requireSupabase(); const {data,error}=await client.from('post_comments_public').select('*').eq('post_id',postId).order('created_at'); fail(error); return rows(data).map((r):Comment=>({ id:str(r.id),postId:str(r.post_id),authorId:str(r.author_id),authorName:str(r.author_name),authorAvatar:str(r.author_avatar),authorRole:r.author_role==='business_owner'?'owner':'customer',text:str(r.body),likeCount:0,isLiked:false,createdAt:iso(r.created_at),isReply:Boolean(r.parent_comment_id),parentCommentId:str(r.parent_comment_id)||undefined })); },
  async addComment(postId:string,text:string,_authorId:string,_authorName:string,_authorAvatar:string,_authorRole:'customer'|'owner'):Promise<Comment>{ const uid=await userId(); const {data,error}=await requireSupabase().from('post_comments').insert({post_id:postId,author_id:uid,body:text}).select('*').single(); fail(error); const profile=await getPublicProfile(uid); return {id:str(data?.id),postId,authorId:uid,authorName:str(profile.display_name),authorAvatar:str(profile.avatar_url),authorRole:str(profile.role)==='business_owner'?'owner':'customer',text,likeCount:0,isLiked:false,createdAt:iso(data?.created_at)}; },
  async getSaved(){ const uid=await userId(); const {data,error}=await requireSupabase().from('saved_posts').select('post_id').eq('customer_id',uid); fail(error); const ids=new Set(rows(data).map((item)=>str(item.post_id))); return (await loadPosts()).filter((item)=>ids.has(item.id)); },
};
async function getPublicProfile(id:string){ const {data,error}=await requireSupabase().from('public_profiles').select('*').eq('id',id).maybeSingle(); fail(error); return row(data); }

function mapDeal(value:unknown,claimed=new Set<string>(),saved=new Set<string>()):Deal { const r=row(value); const b=row(r.businesses); const id=str(r.id); return {id,businessId:str(r.business_id),businessName:str(b.name),businessUsername:str(b.username),businessAvatar:publicAsset('business-logos',b.logo_url),businessLogo:publicAsset('business-logos',b.logo_url),businessCategory:str(b.category),title:str(r.title),description:str(r.description),mediaUrl:publicAsset('deal-media',r.media_path),originalPrice:num(r.original_price),offerPrice:num(r.offer_price),discount:num(r.discount_percent),startDate:iso(r.starts_at),endDate:iso(r.ends_at),maxClaims:num(r.max_claims),claimedCount:num(r.claimed_count),terms:str(r.terms),ctaLabel:str(r.cta_label,'Claim Deal'),isClaimed:claimed.has(id),isSaved:saved.has(id),category:str(b.category),city:str(b.city),rating:num(b.rating),createdAt:iso(r.created_at)}; }
async function loadDeals(){ const client=requireSupabase(); const {data,error}=await client.from('deals').select('*, businesses(name,username,logo_url,category,city)').eq('status','published').order('created_at',{ascending:false}); fail(error); const base=rows(data); const ids=base.map((item)=>str(item.id)); let claimed=new Set<string>(),saved=new Set<string>(); const {data:auth}=await client.auth.getSession(); const current=auth.session?.user.id; if(current&&ids.length){ const [c,s]=await Promise.all([client.from('deal_claims').select('deal_id').eq('customer_id',current).in('deal_id',ids),client.from('saved_deals').select('deal_id').eq('customer_id',current).in('deal_id',ids)]); claimed=new Set(rows(c.data).map((item)=>str(item.deal_id))); saved=new Set(rows(s.data).map((item)=>str(item.deal_id))); } return base.map((item)=>mapDeal(item,claimed,saved)); }
export const supabaseDealService={ getAll:loadDeals,async create(businessId:string,input:DealCreateInput,file?:File){let path='',dealId='';try{if(file)path=await uploadBusinessAsset('deal-media',businessId,file);const{data,error}=await requireSupabase().from('deals').insert({business_id:businessId,title:input.title,description:input.description,media_path:path||null,original_price:input.originalPrice,offer_price:input.offerPrice,discount_percent:input.discount,starts_at:input.startsAt,ends_at:input.endsAt,max_claims:input.maxClaims||null,terms:input.terms||'',cta_label:input.ctaLabel||'Claim Deal',status:'published'}).select('id').single();fail(error);dealId=str(data?.id);const created=await this.getById(dealId);if(!created)throw new Error('Deal was inserted but could not be verified.');return created;}catch(error){if(dealId)await requireSupabase().from('deals').delete().eq('id',dealId);await removeAsset('deal-media',path);throw error;}}, async getByBusiness(id:string){return(await loadDeals()).filter((item)=>item.businessId===id);},async getById(id:string){return(await loadDeals()).find((item)=>item.id===id)??null;},async getTrending(){return(await loadDeals()).sort((a,b)=>b.discount-a.discount);},async claim(id:string){const{data,error}=await requireSupabase().rpc('claim_deal',{target_deal_id:id});fail(error);const r=row(data);const deal=await this.getById(id);if(!deal)throw new Error('Claim was created but the deal could not be refreshed.');const claim:DealClaim={id:str(r.id),dealId:id,dealTitle:deal.title,businessId:deal.businessId,businessName:deal.businessName,businessLogo:deal.businessLogo,customerId:str(r.customer_id),customerName:'',claimCode:str(r.claim_code),claimedAt:iso(r.claimed_at),status:str(r.status,'claimed') as DealClaim['status']};return{deal,claim};},async toggleSave(id:string){await toggleOwn('saved_deals','deal_id',id);return this.getById(id);},async getSaved(){return(await loadDeals()).filter((item)=>item.isSaved);},async search(query:string){const q=query.toLowerCase();return(await loadDeals()).filter((item)=>`${item.title} ${item.description} ${item.businessName} ${item.category}`.toLowerCase().includes(q));} };

function mapStory(value:unknown):Story { const r=row(value),b=row(r.businesses); return {id:str(r.id),businessId:str(r.business_id),businessName:str(b.name),businessUsername:str(b.username),businessAvatar:publicAsset('business-logos',b.logo_url),businessLogo:publicAsset('business-logos',b.logo_url),mediaUrl:publicAsset('story-media',r.media_path),mediaType:str(r.story_type)==='video'?'video':'image',caption:str(r.caption)||undefined,createdAt:iso(r.created_at),expiresAt:iso(r.expires_at),viewCount:num(r.view_count),interactionCount:0,hasUnseen:true,dealId:str(r.deal_id)||undefined,highlights:[]}; }
async function loadStories(){const{data,error}=await requireSupabase().from('stories').select('*, businesses(name,username,logo_url)').eq('status','published').gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false});fail(error);return rows(data).map(mapStory);}
export const supabaseStoryService={getAll:loadStories,async create(businessId:string,input:StoryCreateInput,file?:File){if(!file)throw new Error('Story media is required.');let path='';try{path=await uploadBusinessAsset('story-media',businessId,file);const{data,error}=await requireSupabase().from('stories').insert({business_id:businessId,story_type:input.storyType,caption:input.caption||null,media_path:path,status:'published'}).select('id').single();fail(error);return str(data?.id);}catch(error){await removeAsset('story-media',path);throw error;}},async getByBusiness(id:string){return(await loadStories()).filter((item)=>item.businessId===id);},async getHighlights(id:string){const{data,error}=await requireSupabase().from('story_highlights').select('*, story_highlight_items(story_id,sort_order)').eq('business_id',id).order('sort_order');fail(error);return rows(data).map((r):StoryHighlight=>({id:str(r.id),businessId:str(r.business_id),title:str(r.title),coverUrl:publicAsset('story-media',r.cover_path),storyIds:rows(r.story_highlight_items).map((item)=>str(item.story_id))}));},async markSeen(storyId:string){const uid=await userId();const{error}=await requireSupabase().from('story_views').upsert({story_id:storyId,viewer_id:uid});fail(error);} };

function mapReview(value:unknown,helpful=new Set<string>()):Review { const r=row(value),reply=row(r.reply),id=str(r.id); return {id,businessId:str(r.business_id),customerId:str(r.customer_id),customerName:str(r.customer_name),customerAvatar:str(r.customer_avatar),rating:num(r.rating),text:str(r.review_text),photoUrl:publicAsset('review-media',r.photo_path)||undefined,likeCount:num(r.helpful_count),reply:reply.id?{id:str(reply.id),text:str(reply.text),createdAt:iso(reply.created_at)}:undefined,createdAt:iso(r.created_at),isHelpful:helpful.has(id)}; }
async function loadReviews(){const client=requireSupabase();const{data,error}=await client.from('reviews_public').select('*').order('created_at',{ascending:false});fail(error);let helpful=new Set<string>();const{data:auth}=await client.auth.getSession();const current=auth.session?.user.id;if(current){const result=await client.from('review_helpful').select('review_id').eq('customer_id',current);helpful=new Set(rows(result.data).map((item)=>str(item.review_id)));}return rows(data).map((item)=>mapReview(item,helpful));}
export const supabaseReviewService={async getByBusiness(id:string){return(await loadReviews()).filter((item)=>item.businessId===id);},async getByCustomer(id:string){return(await loadReviews()).filter((item)=>item.customerId===id);},async add(businessId:string,_customerId:string,_name:string,_avatar:string,rating:number,text:string,photoUrl?:string){const uid=await userId();const{data,error}=await requireSupabase().from('reviews').insert({business_id:businessId,customer_id:uid,rating,review_text:text,photo_path:photoUrl}).select('id').single();fail(error);return(await loadReviews()).find((item)=>item.id===str(data?.id))!;},async reply(reviewId:string,text:string){const review=(await loadReviews()).find((item)=>item.id===reviewId);if(!review)throw new Error('Review unavailable');const{data,error}=await requireSupabase().from('review_replies').insert({review_id:reviewId,business_id:review.businessId,reply_text:text}).select('*').single();fail(error);return{id:str(data?.id),text:str(data?.reply_text),createdAt:iso(data?.created_at)};},async toggleHelpful(id:string){await toggleOwn('review_helpful','review_id',id);return(await loadReviews()).find((item)=>item.id===id)??null;},async getRatingBreakdown(id:string){const list=(await loadReviews()).filter((item)=>item.businessId===id);return{five:list.filter(i=>i.rating===5).length,four:list.filter(i=>i.rating===4).length,three:list.filter(i=>i.rating===3).length,two:list.filter(i=>i.rating===2).length,one:list.filter(i=>i.rating===1).length};} };

export const supabaseFollowService={async getFollowers(businessId:string){const{data,error}=await requireSupabase().rpc('get_business_followers',{target_business_id:businessId});fail(error);return rows(data).map((r):BusinessFollower=>({id:`${businessId}:${str(r.customer_id)}`,customerId:str(r.customer_id),displayName:str(r.display_name),avatarUrl:str(r.avatar_url),businessId,followedAt:iso(r.followed_at),source:str(r.source,'profile') as BusinessFollower['source']}));},async getFollowing(_customerId:string){const uid=await userId();const{data,error}=await requireSupabase().from('business_followers').select('business_id').eq('customer_id',uid);fail(error);const ids=new Set(rows(data).map((item)=>str(item.business_id)));return(await businessQuery()).filter((item)=>ids.has(item.id));},async follow(businessId:string,_customerId:string,_name:string,_avatar:string,source:BusinessFollower['source']='profile'){const uid=await userId();const{error}=await requireSupabase().from('business_followers').upsert({business_id:businessId,customer_id:uid,source},{onConflict:'business_id,customer_id',ignoreDuplicates:true});fail(error);},async unfollow(businessId:string,_customerId:string){const uid=await userId();const{error}=await requireSupabase().from('business_followers').delete().eq('business_id',businessId).eq('customer_id',uid);fail(error);},async isFollowing(businessId:string,_customerId:string){const uid=await userId();const{data,error}=await requireSupabase().from('business_followers').select('business_id').eq('business_id',businessId).eq('customer_id',uid).maybeSingle();fail(error);return Boolean(data);} };

function mapMessage(value:unknown,customerId=''):Message{const r=row(value);return{id:str(r.id),conversationId:str(r.conversation_id),senderId:str(r.sender_user_id),senderType:str(r.sender_user_id)===customerId?'customer':'owner',text:str(r.body)||undefined,imageUrl:str(r.media_path)||undefined,sharedDealId:str(r.shared_deal_id)||undefined,sharedPostId:str(r.shared_post_id)||undefined,isRead:Boolean(r.read_at),createdAt:iso(r.created_at)};}
async function mapMessageWithMedia(value:unknown,customerId=''){const message=mapMessage(value,customerId);if(message.imageUrl){const{data,error}=await requireSupabase().storage.from('message-media').createSignedUrl(message.imageUrl,3600);fail(error);message.imageUrl=data?.signedUrl;}return message;}
export const supabaseMessageService={
  async getConversations(){const uid=await userId();const client=requireSupabase();const{data,error}=await client.from('conversations').select('*, businesses(name,username,logo_url,owner_id)').order('updated_at',{ascending:false});fail(error);const list=rows(data);const customerIds=[...new Set(list.map((item)=>str(item.customer_id)))];const profiles=new Map<string,Row>();if(customerIds.length){const result=await client.from('public_profiles').select('*').in('id',customerIds);fail(result.error);for(const item of rows(result.data))profiles.set(str(item.id),item);}const conversationIds=list.map((item)=>str(item.id));const unread=new Map<string,number>();const latest=new Map<string,Row>();if(conversationIds.length){const result=await client.from('messages').select('conversation_id,sender_user_id,body,created_at,read_at').in('conversation_id',conversationIds).order('created_at',{ascending:false});fail(result.error);for(const message of rows(result.data)){const id=str(message.conversation_id);if(!latest.has(id))latest.set(id,message);if(str(message.sender_user_id)!==uid&&!message.read_at)unread.set(id,(unread.get(id)??0)+1);}}return list.map((r):Conversation=>{const b=row(r.businesses),p=profiles.get(str(r.customer_id))??{},last=latest.get(str(r.id));const customerSide=str(r.customer_id)===uid;return{id:str(r.id),businessId:str(r.business_id),businessName:str(b.name),businessUsername:str(b.username),businessAvatar:publicAsset('business-logos',b.logo_url),businessLogo:publicAsset('business-logos',b.logo_url),customerId:str(r.customer_id),customerName:str(p.display_name),customerAvatar:str(p.avatar_url),lastMessage:last?str(last.body,'Attachment'):'Start the conversation',lastMessageAt:last?iso(last.created_at):iso(r.updated_at),unreadCount:unread.get(str(r.id))??0,isCustomerSide:customerSide,isOnline:false};});},
  async searchContacts(query:string){const uid=await userId();const client=requireSupabase();const{data:profile,error:profileError}=await client.from('profiles').select('role').eq('id',uid).single();fail(profileError);const q=query.trim().toLowerCase();if(str(profile?.role)==='customer'){const businesses=await businessQuery();return businesses.filter((item)=>`${item.name} ${item.username} ${item.category}`.toLowerCase().includes(q)).slice(0,12).map((item)=>({id:item.id,name:item.name,username:item.username,avatar:item.logoUrl,kind:'business' as const,businessId:item.id}));}const{data:owned,error:ownedError}=await client.from('businesses').select('id').eq('owner_id',uid).limit(1).single();fail(ownedError);const businessId=str(owned?.id);const result=await client.rpc('get_business_followers',{target_business_id:businessId});fail(result.error);return rows(result.data).filter((item)=>str(item.display_name).toLowerCase().includes(q)).slice(0,12).map((item)=>({id:str(item.customer_id),name:str(item.display_name),username:'',avatar:str(item.avatar_url),kind:'customer' as const,businessId}));},
  async startConversation(businessId:string,customerId?:string){const{data,error}=await requireSupabase().rpc('start_conversation',{target_business_id:businessId,target_customer_id:customerId??null});fail(error);const id=str((data as Row)?.id);return (await this.getConversations()).find((item)=>item.id===id)??null;},
  async getMessages(id:string){const client=requireSupabase();const{data:conversation,error:conversationError}=await client.from('conversations').select('customer_id').eq('id',id).single();fail(conversationError);const{data,error}=await client.from('messages').select('*').eq('conversation_id',id).order('created_at');fail(error);return Promise.all(rows(data).map((item)=>mapMessageWithMedia(item,str(conversation?.customer_id))));},
  async sendMessage(id:string,_sender:string,_type:'customer'|'owner',text:string){const client=requireSupabase(),uid=await userId();const{data:conversation,error:conversationError}=await client.from('conversations').select('customer_id').eq('id',id).single();fail(conversationError);const{data,error}=await client.from('messages').insert({conversation_id:id,sender_user_id:uid,body:text}).select('*').single();fail(error);return mapMessage(data,str(conversation?.customer_id));},
  async sendMedia(id:string,file:File){const client=requireSupabase(),uid=await userId();let path='';try{const{data:conversation,error:conversationError}=await client.from('conversations').select('customer_id').eq('id',id).single();fail(conversationError);path=await uploadUserAsset('message-media',uid,file);const{data,error}=await client.from('messages').insert({conversation_id:id,sender_user_id:uid,media_path:path}).select('*').single();fail(error);return await mapMessageWithMedia(data,str(conversation?.customer_id));}catch(error){await removeAsset('message-media',path);throw error;}},
  async markRead(id:string){const uid=await userId();const{error}=await requireSupabase().from('messages').update({read_at:new Date().toISOString()}).eq('conversation_id',id).neq('sender_user_id',uid).is('read_at',null);fail(error);},
  subscribe(id:string,customerId:string,onMessage:(message:Message)=>void){const client=requireSupabase();let channel:ReturnType<typeof client.channel>|null=null;let stopped=false;void(async()=>{try{const{data:{session},error}=await client.auth.getSession();fail(error);if(stopped||!session?.access_token)return;await client.realtime.setAuth(session.access_token);if(stopped)return;channel=client.channel(`conversation:${id}:${session.user.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${id}`},(payload)=>{if(payload.new)void mapMessageWithMedia(payload.new,customerId).then(onMessage);}).subscribe();}catch(err){console.error('[Realtime] Subscription error:',err);}})();return()=>{stopped=true;if(channel)void client.removeChannel(channel);};}
};

function mapNotification(value:unknown):Notification{const r=row(value),b=row(r.businesses),entityType=str(r.entity_type),entityId=str(r.entity_id),rawType=str(r.type);const actionLink=rawType==='bill_requested'?`/business/dashboard?request=${entityId}`:rawType==='payment_confirmation_request'?'/business/dashboard':rawType==='bill_ready'||rawType==='payment_success'||rawType==='payment_not_received'?`/customer?bill=${entityId}`:entityType==='conversation'?`/messages?conversation=${entityId}`:str(b.username)?`/business/${str(b.username)}`:undefined;return{id:str(r.id),type:notificationType(rawType),title:str(r.title),body:str(r.body),businessAvatar:publicAsset('business-logos',b.logo_url)||undefined,businessId:str(r.business_id)||undefined,businessUsername:str(b.username)||undefined,entityType:entityType||undefined,entityId:entityId||undefined,isRead:Boolean(r.read_at),createdAt:iso(r.created_at),actionLabel:rawType==='bill_requested'?'Add Bill':rawType==='payment_confirmation_request'?'Review Payment':rawType==='bill_ready'?'View Bill':undefined,actionLink};}
export const supabaseNotificationService={async getAll(){const id=await userId();const{data,error}=await requireSupabase().from('notifications').select('*, businesses(username,logo_url)').eq('recipient_user_id',id).order('created_at',{ascending:false});fail(error);return rows(data).map(mapNotification);},async markRead(notificationId:string){const id=await userId();const{error}=await requireSupabase().from('notifications').update({read_at:new Date().toISOString()}).eq('id',notificationId).eq('recipient_user_id',id);fail(error);},async markAllRead(){const id=await userId();const{error}=await requireSupabase().from('notifications').update({read_at:new Date().toISOString()}).eq('recipient_user_id',id).is('read_at',null);fail(error);},async getUnreadCount(){const id=await userId();const{count,error}=await requireSupabase().from('notifications').select('*',{count:'exact',head:true}).eq('recipient_user_id',id).is('read_at',null);fail(error);return count??0;},subscribe(onNotification:(notification:Notification)=>void){const client=requireSupabase();let channel:ReturnType<typeof client.channel>|null=null;let stopped=false;void(async()=>{const{data:{session},error}=await client.auth.getSession();fail(error);if(stopped||!session?.access_token)return;const recipientId=session.user.id;await client.realtime.setAuth(session.access_token);if(stopped)return;channel=client.channel(`notifications:${recipientId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`recipient_user_id=eq.${recipientId}`},(payload)=>{if(payload.new&&str(payload.new.recipient_user_id)===recipientId)onNotification(mapNotification(payload.new));}).subscribe();})();return()=>{stopped=true;if(channel)void client.removeChannel(channel);};} };
function notificationType(value:string):Notification['type']{const map:Record<string,Notification['type']>={new_follower:'new_follower',new_review:'new_review',review_reply:'review_reply',new_message:'new_dm',new_deal:'new_deal',new_story:'new_story',reward:'reward_unlocked',reward_unlocked:'reward_unlocked',fe_coins_earned:'reward_unlocked',referral:'referral_update',subscription:'subscription_notice',bill_requested:'new_post',bill_ready:'new_post',payment_success:'reward_unlocked'};return map[value]??'new_post';}

export const supabaseQRService={async getByBusiness(id:string){const{data,error}=await requireSupabase().from('qr_codes').select('*, businesses(name,logo_url)').eq('business_id',id).maybeSingle();fail(error);if(!data)return null;const r=row(data),b=row(r.businesses);return{id:str(r.id),businessId:id,businessName:str(b.name),businessLogo:publicAsset('business-logos',b.logo_url),code:str(r.code),shortUrl:`founder.env/q/${str(r.code)}`,scans:0,createdAt:iso(r.created_at)};},async getByCode(code:string){const{data,error}=await requireSupabase().rpc('resolve_and_track_qr',{target_code:code,target_source:'qr',target_metadata:{user_agent:navigator.userAgent.slice(0,200)}});fail(error);const result=rows(data)[0];return result?supabaseBusinessService.getById(str(result.business_id)):null;},async getScans(id:string){const qr=await this.getByBusiness(id);if(!qr)return[];const{data,error}=await requireSupabase().from('qr_scans').select('*').eq('qr_code_id',qr.id).order('created_at',{ascending:false});fail(error);return rows(data).map((r):QRScan=>({id:str(r.id),qrCodeId:qr.id,businessId:id,scannedAt:iso(r.created_at),source:str(r.source,'qr') as QRScan['source'],resultedInFollow:false}));} };

export const supabaseRewardService={async getByCustomer(_id:string){const uid=await userId();const{data,error}=await requireSupabase().from('reward_claims').select('*, reward_campaigns(*, businesses(name,logo_url))').eq('customer_id',uid).order('created_at',{ascending:false});fail(error);return rows(data).map(mapReward);},async getByBusiness(id:string){const{data,error}=await requireSupabase().from('reward_claims').select('*, reward_campaigns!inner(*, businesses(name,logo_url))').eq('reward_campaigns.business_id',id);fail(error);return rows(data).map(mapReward);},async redeem(_id:string):Promise<{state:RedemptionState;reward?:Reward}>{throw new Error('Secure reward redemption will be enabled through a server function; the client cannot mark rewards redeemed.');} };
function mapReward(value:unknown):Reward{const r=row(value),c=row(r.reward_campaigns),b=row(c.businesses);return{id:str(r.id),businessId:str(c.business_id),businessName:str(b.name),businessLogo:publicAsset('business-logos',b.logo_url),customerId:str(r.customer_id),title:str(c.name),description:str(c.reward_type),type:'deal',status:str(r.status)==='redeemed'?'used':str(r.status)==='expired'?'expired':'available',expiryDate:iso(c.ends_at),terms:'',value:str(c.reward_value),redeemedAt:str(r.redeemed_at)||undefined,code:str(r.reward_code)};}

export const supabaseReferralService={async getByCustomer(_id:string){const uid=await userId();const{data,error}=await requireSupabase().from('referrals').select('*, referral_campaigns(*, businesses(name,logo_url))').eq('referrer_customer_id',uid).order('created_at',{ascending:false});fail(error);return rows(data).map(mapReferral);},async getByBusiness(id:string){const{data,error}=await requireSupabase().from('referrals').select('*, referral_campaigns(*, businesses(name,logo_url))').eq('business_id',id);fail(error);return rows(data).map(mapReferral);} };
function mapReferral(value:unknown):Referral{const r=row(value),c=row(r.referral_campaigns),b=row(c.businesses);return{id:str(r.id),businessId:str(r.business_id),businessName:str(b.name),businessLogo:publicAsset('business-logos',b.logo_url),customerId:str(r.referrer_customer_id),customerName:'',referralCode:str(r.referral_code),referralLink:`founder.env/ref/${str(r.referral_code)}`,friendReward:str(c.friend_reward),referrerReward:str(c.referrer_reward),state:str(r.status,'pending') as Referral['state'],createdAt:iso(r.created_at),qualifiedAt:str(r.qualified_at)||undefined,rewardedAt:str(r.rewarded_at)||undefined};}

export const supabaseLoyaltyService={async getByCustomer(_id:string){const uid=await userId();const{data,error}=await requireSupabase().from('loyalty_members').select('*, loyalty_programs(*, businesses(name,logo_url)), loyalty_transactions(*)').eq('customer_id',uid);fail(error);return rows(data).map(mapLoyalty);},async getByBusiness(id:string){const{data,error}=await requireSupabase().from('loyalty_programs').select('*, businesses(name,logo_url), loyalty_members(*, loyalty_transactions(*))').eq('business_id',id);fail(error);return rows(data).map((r)=>mapLoyalty({loyalty_programs:r,loyalty_transactions:[]}));} };
function mapLoyalty(value:unknown):LoyaltyProgram{const outer=row(value),p=row(outer.loyalty_programs),b=row(p.businesses),tx=rows(outer.loyalty_transactions);const current=tx.reduce((sum,item)=>sum+num(item.amount),0);return{id:str(p.id),businessId:str(p.business_id),businessName:str(b.name),businessLogo:publicAsset('business-logos',b.logo_url),name:str(p.name),type:str(p.program_type,'visit') as LoyaltyProgram['type'],totalSteps:num(p.reward_threshold),currentSteps:current,rewardLabel:str(p.reward_label),nextReward:str(p.reward_label),history:tx.map((item)=>({date:iso(item.created_at),action:str(item.transaction_type),points:num(item.amount)})),terms:str(p.terms),isActive:str(p.status)==='published'};}

export const supabaseScratchService={async getAvailable(){const{data,error}=await requireSupabase().from('scratch_campaigns').select('*, businesses(name,logo_url)').eq('status','published').lte('starts_at',new Date().toISOString()).gte('ends_at',new Date().toISOString());fail(error);return rows(data).map(mapScratchCampaign);},async getByBusiness(id:string){const{data,error}=await requireSupabase().from('scratch_campaigns').select('*, businesses(name,logo_url)').eq('business_id',id);fail(error);return rows(data).map(mapScratchCampaign);},async play(id:string){const client=requireSupabase();const uid=await userId();const{data:claim,error:claimError}=await client.from('deal_claims').select('id').eq('customer_id',uid).in('status',['claimed','redeemed']).order('claimed_at',{ascending:false}).limit(1).maybeSingle();fail(claimError);if(!claim)throw new Error('An eligible deal claim is required to play Scratch & Win.');const{data,error}=await client.functions.invoke('scratch-play',{body:{campaignId:id,dealClaimId:claim.id}});if(error)throw error;const result=row(row(data).data);return{id:str(result.id),campaignId:id,businessName:'',businessLogo:'',outcome:str(result.outcome_key) as ScratchResult['outcome'],label:str(result.outcome_label),isWin:bool(result.is_win),date:iso(result.created_at)};},async getHistory(_id:string){const uid=await userId();const{data,error}=await requireSupabase().from('scratch_plays').select('*').eq('customer_id',uid).order('created_at',{ascending:false});fail(error);return rows(data).map((r):ScratchResult=>({id:str(r.id),campaignId:str(r.campaign_id),businessName:'',businessLogo:'',outcome:str(r.outcome_key) as ScratchResult['outcome'],label:str(r.outcome_label),isWin:bool(r.is_win),date:iso(r.created_at)}));} };
function mapScratchCampaign(value:unknown):ScratchCampaign{const r=row(value),b=row(r.businesses);return{id:str(r.id),businessId:str(r.business_id),businessName:str(b.name),businessLogo:publicAsset('business-logos',b.logo_url),name:str(r.name),rewards:rows(r.outcomes).map((o)=>({outcome:str(o.key) as ScratchCampaign['rewards'][number]['outcome'],label:str(o.label),probability:num(o.weight)})),maxWins:num(r.max_plays),validity:iso(r.ends_at),minimumBill:0,isActive:str(r.status)==='published',winsToday:0,totalPlays:0};}

export const supabaseVideoService={async create(businessId:string,input:ClipCreateInput,file:File){let path='';try{path=await uploadBusinessAsset('deal-media',businessId,file);const{data,error}=await requireSupabase().from('deal_clips').insert({business_id:businessId,deal_id:input.dealId||null,video_path:path,caption:input.caption,music:input.music||null,status:'published'}).select('id').single();fail(error);return str(data?.id);}catch(error){await removeAsset('deal-media',path);throw error;}},async getAll(){const{data,error}=await requireSupabase().from('deal_clips').select('*, businesses(name,username,logo_url,category,location), deals(title)').eq('status','published').order('created_at',{ascending:false});fail(error);return rows(data).map(mapClip);},async getByBusiness(id:string){return(await this.getAll()).filter((item)=>item.businessId===id);},async toggleLike(id:string){await toggleOwn('deal_clip_likes','clip_id',id);return(await this.getAll()).find((item)=>item.id===id)??null;},async toggleSave(id:string){await toggleOwn('saved_deal_clips','clip_id',id);return(await this.getAll()).find((item)=>item.id===id)??null;} };
function mapClip(value:unknown):VideoClip{const r=row(value),b=row(r.businesses),d=row(r.deals);return{id:str(r.id),businessId:str(r.business_id),businessName:str(b.name),businessUsername:str(b.username),businessAvatar:publicAsset('business-logos',b.logo_url),businessLogo:publicAsset('business-logos',b.logo_url),businessCategory:str(b.category),businessLocation:str(b.location),videoUrl:publicAsset('deal-media',r.video_path),thumbnailUrl:publicAsset('deal-media',r.thumbnail_path),caption:str(r.caption),dealId:str(r.deal_id)||undefined,dealTitle:str(d.title)||undefined,likeCount:0,commentCount:0,shareCount:0,saveCount:0,isLiked:false,isSaved:false,isFollowing:false,music:str(r.music)||undefined,createdAt:iso(r.created_at)};}

export const supabaseTemplateService={async getAll(){const{data,error}=await requireSupabase().from('business_templates').select('*').eq('is_active',true);fail(error);return rows(data).map(mapTemplate);},async getById(id:TemplateId){return(await this.getAll()).find((item)=>item.id===id)??(await this.getAll())[0];}};
function mapTemplate(value:unknown):BusinessTemplateConfig{const r=row(value),c=row(r.configuration);return{id:str(r.key) as TemplateId,name:str(r.name),description:str(c.description),accentColor:str(c.accentColor,'#109a59'),fontFamily:str(c.fontFamily,'Inter'),heroStyle:str(c.heroStyle,'minimal') as BusinessTemplateConfig['heroStyle'],cardStyle:str(c.cardStyle,'rounded') as BusinessTemplateConfig['cardStyle'],sectionOrder:Array.isArray(c.sectionOrder)?c.sectionOrder.map(String):['about','featured','hours','location','reviews'],imageTreatment:str(c.imageTreatment,'natural') as BusinessTemplateConfig['imageTreatment'],defaultThemeMode:str(c.defaultThemeMode,'light') as BusinessTemplateConfig['defaultThemeMode']};}
export const supabaseCategoryService={async getAll():Promise<Category[]>{return staticCategories;}};

export const supabaseCustomerService={async getCurrent():Promise<CustomerAccount>{const uid=await userId();const{data,error}=await requireSupabase().from('profiles').select('*').eq('id',uid).single();fail(error);const r=row(data);const[follows,rewards,reviews,saved]=await Promise.all([count('business_followers','customer_id',uid),count('reward_claims','customer_id',uid),count('reviews','customer_id',uid),count('saved_posts','customer_id',uid)]);return{id:uid,displayName:str(r.display_name),email:str(r.email_private),avatarUrl:publicAsset('customer-avatars',r.avatar_url),createdAt:iso(r.created_at),lastActiveAt:new Date().toISOString(),followingCount:follows,rewardsCount:rewards,reviewsCount:reviews,savedCount:saved,status:str(r.status,'active') as CustomerAccount['status']};}};
async function count(table:string,column:string,value:string){const{count,error}=await requireSupabase().from(table).select('*',{count:'exact',head:true}).eq(column,value);fail(error);return count??0;}
export const supabaseOwnerService={async getCurrent():Promise<BusinessOwner>{const uid=await userId();const{data,error}=await requireSupabase().from('profiles').select('*').eq('id',uid).single();fail(error);const businesses=await supabaseBusinessService.getByOwner(uid);const r=row(data);return{id:uid,name:str(r.display_name),email:str(r.email_private),phone:'',businessIds:businesses.map((item)=>item.id)};}};

export const supabaseSubscriptionService={async getByBusiness(id:string){const{data,error}=await requireSupabase().from('subscriptions').select('*, businesses(name)').eq('business_id',id).maybeSingle();fail(error);return data?mapSubscription(data):null;},async getPayments(id:string){const{data,error}=await requireSupabase().from('payments').select('*, businesses(name), invoices(invoice_number)').eq('business_id',id).order('created_at',{ascending:false});fail(error);return rows(data).map(mapPayment);} };
function mapSubscription(value:unknown):Subscription{const r=row(value),b=row(r.businesses);return{id:str(r.id),businessId:str(r.business_id),businessName:str(b.name),plan:str(r.plan,'lite') as Subscription['plan'],status:subscriptionUiStatus(str(r.status)),startDate:iso(r.started_at),expiryDate:iso(r.current_period_end),nextBillingDate:str(r.current_period_end)||str(r.subscription_start_at)||undefined,amount:Number(r.monthly_amount_paise??0)/100,autoRenew:r.autopay_authorized===true&&r.cancel_at_period_end!==true,setupFeePaid:Boolean(r.setup_fee_paid),setupFeeAmount:Number(r.setup_fee_amount_paise??0)/100,monthlyAmount:Number(r.monthly_amount_paise??0)/100,autopayAuthorized:Boolean(r.autopay_authorized),providerStatus:str(r.provider_status),totalCount:Number(r.total_count??0),paidCount:Number(r.paid_count??0),cancelAtPeriodEnd:Boolean(r.cancel_at_period_end),activationType:str(r.activation_type,'pending') as Subscription['activationType']};}
function subscriptionUiStatus(value:string):Subscription['status']{return value==='active'?'active':value==='past_due'?'failed':value==='grace_period'?'expiring':value==='cancelled'?'suspended':'expired';}
function mapPayment(value:unknown):Payment{const r=row(value),b=row(r.businesses),invoice=rows(r.invoices)[0]??{};return{id:str(r.external_payment_id,str(r.id)),businessId:str(r.business_id),businessName:str(b.name),amount:num(r.amount),type:str(r.type) as Payment['type'],status:str(r.status) as Payment['status'],date:iso(r.created_at),invoiceId:str(invoice.invoice_number),method:str(r.provider)};}

export const supabaseAdminService={async getDashboardMetrics():Promise<AnalyticsMetric[]>{const[b,c,s,p]=await Promise.all([countAll('businesses'),countAll('profiles','role','customer'),countAll('subscriptions','status','active'),countAll('payments','status','failed')]);return[{label:'Total Businesses',value:b,change:0,trend:'flat'},{label:'Total Customers',value:c,change:0,trend:'flat'},{label:'Active Pro',value:s,change:0,trend:'flat'},{label:'Failed Payments',value:p,change:0,trend:'flat'}];},getBusinesses:businessQuery,async getCustomers(){const{data,error}=await requireSupabase().from('profiles').select('*').eq('role','customer');fail(error);return rows(data).map((r):CustomerAccount=>({id:str(r.id),displayName:str(r.display_name),email:str(r.email_private),avatarUrl:str(r.avatar_url),createdAt:iso(r.created_at),lastActiveAt:iso(r.updated_at),followingCount:0,rewardsCount:0,reviewsCount:0,savedCount:0,status:str(r.status) as CustomerAccount['status']}));},async getPayments(){const{data,error}=await requireSupabase().from('payments').select('*, businesses(name), invoices(invoice_number)');fail(error);return rows(data).map(mapPayment);},async getSubscriptions(){const{data,error}=await requireSupabase().from('subscriptions').select('*, businesses(name)');fail(error);return rows(data).map(mapSubscription);},async getReports(){const client=requireSupabase();const{data,error}=await client.from('reports').select('*').order('created_at',{ascending:false});fail(error);const reportRows=rows(data);const reporterIds=[...new Set(reportRows.map((r)=>str(r.reporter_id)).filter(Boolean))];const profiles=new Map<string,Row>();if(reporterIds.length){const result=await client.from('profiles').select('id,display_name,avatar_url').in('id',reporterIds);fail(result.error);for(const profile of rows(result.data))profiles.set(str(profile.id),profile);}return reportRows.map((r):Report=>{const p=profiles.get(str(r.reporter_id))??{};return{id:str(r.id),reporterName:str(p.display_name),reporterAvatar:str(p.avatar_url),entityType:str(r.entity_type) as Report['entityType'],entityId:str(r.entity_id),entityPreview:str(r.details),reason:str(r.reason) as Report['reason'],status:str(r.status) as Report['status'],createdAt:iso(r.created_at)};});}};
async function countAll(table:string,column?:string,value?:string){let query=requireSupabase().from(table).select('*',{count:'exact',head:true});if(column&&value)query=query.eq(column,value);const{count,error}=await query;fail(error);return count??0;}

export const supabaseAnalyticsService={async getOwnerMetrics(businessId:string):Promise<{metrics:AnalyticsMetric[];series:AnalyticsSeries[];trafficSources:TrafficSource[]}>{const client=requireSupabase(),since=new Date(Date.now()-30*86400000).toISOString();const [followers,newFollowers,relationships,requests,bills,paid,coins,eventsResult]=await Promise.all([countAll('business_followers','business_id',businessId),client.from('business_followers').select('*',{count:'exact',head:true}).eq('business_id',businessId).gte('followed_at',since),countAll('customer_business_relationships','business_id',businessId),countAll('bill_requests','business_id',businessId),countAll('bills','business_id',businessId),client.from('bills').select('final_amount,customer_id').eq('business_id',businessId).eq('payment_status','paid'),client.from('fe_coin_accounts').select('balance').eq('business_id',businessId).eq('account_type','business').maybeSingle(),client.from('analytics_events').select('event_type,metadata,created_at').eq('business_id',businessId).gte('created_at',since)]);fail(newFollowers.error);fail(paid.error);fail(coins.error);fail(eventsResult.error);const paidRows=rows(paid.data),sales=paidRows.reduce((sum,item)=>sum+num(item.final_amount),0),repeatCustomers=[...new Set(paidRows.map((item)=>str(item.customer_id)))].filter((customer)=>paidRows.filter((item)=>str(item.customer_id)===customer).length>1).length;const metrics:AnalyticsMetric[]=[{label:'Followers',value:followers,change:0,trend:'flat'},{label:'New followers',value:newFollowers.count??0,change:0,trend:'flat'},{label:'Total customers',value:relationships,change:0,trend:'flat'},{label:'Bill requests',value:requests,change:0,trend:'flat'},{label:'Bills created',value:bills,change:0,trend:'flat'},{label:'Paid bills',value:paidRows.length,change:0,trend:'flat'},{label:'Attributed sales',value:sales,change:0,trend:'flat',format:'currency'},{label:'Repeat customers',value:repeatCustomers,change:0,trend:'flat'},{label:'FE Coins',value:num(coins.data?.balance),change:0,trend:'flat'}];const events=rows(eventsResult.data),series:AnalyticsSeries[]=[{label:'Activity (30 days)',data:Array.from({length:30},(_,index)=>{const date=new Date(Date.now()-(29-index)*86400000),key=date.toISOString().slice(0,10);return{label:date.toLocaleDateString(undefined,{month:'short',day:'numeric'}),value:events.filter((item)=>str(item.created_at).slice(0,10)===key).length};})}];return{metrics,series,trafficSources:[]};}};

export const supabaseStaticServices = { category: supabaseCategoryService };
