import type { AIContentGeneration, PosterLayout, RendererData } from '@/services/aiContentService';

export const POSTER_SIZE=1080;
const FONT='Inter, "Noto Sans Devanagari", "Nirmala UI", Mangal, system-ui, sans-serif';
type Box={x:number;y:number;width:number;height:number};
type TextOptions={maxSize:number;minSize:number;weight:number;lineHeight:number;maxLines:number;color?:string;align?:CanvasTextAlign;uppercase?:boolean};

function clean(value:unknown){return typeof value==='string'?value.replace(/\s+/g,' ').trim():'';}
function hash(value:string){let result=2166136261;for(const char of value){result^=char.charCodeAt(0);result=Math.imul(result,16777619);}return result>>>0;}
function seeded(seed:number){let state=seed||1;return()=>{state^=state<<13;state^=state>>>17;state^=state<<5;return(state>>>0)/4294967296;};}
function rounded(ctx:CanvasRenderingContext2D,x:number,y:number,width:number,height:number,radius:number,fill:string,stroke?:string){ctx.beginPath();ctx.roundRect(x,y,width,height,radius);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke();}}
function alpha(hex:string,opacity:number){const value=hex.replace('#','');if(value.length!==6)return`rgba(255,255,255,${opacity})`;return`rgba(${parseInt(value.slice(0,2),16)},${parseInt(value.slice(2,4),16)},${parseInt(value.slice(4,6),16)},${opacity})`;}
function tokens(text:string){const value=clean(text);return value?value.split(/(\s+)/).filter(Boolean):[];}
function wrapAll(ctx:CanvasRenderingContext2D,text:string,width:number){const pieces=tokens(text),lines:string[]=[];let line='';for(const piece of pieces){const next=(line+piece).trimStart();if(ctx.measureText(next).width<=width){line=next;continue;}if(line.trim()){lines.push(line.trim());line='';}if(ctx.measureText(piece.trim()).width<=width){line=piece.trimStart();continue;}for(const character of [...piece.trim()]){const candidate=line+character;if(ctx.measureText(candidate).width>width&&line){lines.push(line);line=character;}else line=candidate;}}if(line.trim())lines.push(line.trim());return lines;}
export function fitText(ctx:CanvasRenderingContext2D,text:string,box:Box,options:TextOptions){const value=options.uppercase?clean(text).toLocaleUpperCase():clean(text);let size=options.maxSize,result:string[]=[];for(;size>=options.minSize;size-=2){ctx.font=`${options.weight} ${size}px ${FONT}`;result=wrapAll(ctx,value,box.width);if(result.length<=options.maxLines&&result.length*size*options.lineHeight<=box.height)break;}size=Math.max(size,options.minSize);if(result.length>options.maxLines){result=result.slice(0,options.maxLines);let last=result[options.maxLines-1];while(last&&ctx.measureText(`${last}…`).width>box.width)last=last.slice(0,-1);result[options.maxLines-1]=`${last.trimEnd()}…`;}return{lines:result,size,lineHeight:size*options.lineHeight};}
function drawText(ctx:CanvasRenderingContext2D,text:string,box:Box,options:TextOptions){const fitted=fitText(ctx,text,box,options);ctx.save();ctx.fillStyle=options.color||'#fff';ctx.font=`${options.weight} ${fitted.size}px ${FONT}`;ctx.textAlign=options.align||'left';ctx.textBaseline='top';const x=options.align==='center'?box.x+box.width/2:options.align==='right'?box.x+box.width:box.x;fitted.lines.forEach((line,index)=>ctx.fillText(line,x,box.y+index*fitted.lineHeight));ctx.restore();return fitted;}
async function loadImage(url:string){if(!url)return null;return new Promise<HTMLImageElement|null>(resolve=>{const image=new Image();let settled=false;const finish=(value:HTMLImageElement|null)=>{if(settled)return;settled=true;window.clearTimeout(timer);resolve(value);};const timer=window.setTimeout(()=>finish(null),2500);image.crossOrigin='anonymous';image.onload=()=>finish(image);image.onerror=()=>finish(null);image.src=url;});}
function drawCover(ctx:CanvasRenderingContext2D,image:HTMLImageElement,box:Box){const scale=Math.max(box.width/image.naturalWidth,box.height/image.naturalHeight),width=image.naturalWidth*scale,height=image.naturalHeight*scale;ctx.drawImage(image,box.x+(box.width-width)/2,box.y+(box.height-height)/2,width,height);}
function drawContain(ctx:CanvasRenderingContext2D,image:HTMLImageElement,box:Box){const scale=Math.min(box.width/image.naturalWidth,box.height/image.naturalHeight),width=image.naturalWidth*scale,height=image.naturalHeight*scale;ctx.drawImage(image,box.x+(box.width-width)/2,box.y+(box.height-height)/2,width,height);}
function layoutFor(generation:AIContentGeneration):PosterLayout{return generation.creative.layout||({offer:'offer',festival:'festival',product_service:'product',announcement:'announcement',today:'daily',custom:'product'} as const)[generation.type]||'daily';}

function paintBackground(ctx:CanvasRenderingContext2D,colors:[string,string,string],seed:number){const gradient=ctx.createLinearGradient(30,0,1050,1080);gradient.addColorStop(0,colors[0]);gradient.addColorStop(.56,colors[1]);gradient.addColorStop(1,colors[0]);ctx.fillStyle=gradient;ctx.fillRect(0,0,POSTER_SIZE,POSTER_SIZE);const random=seeded(seed);for(let index=0;index<5;index++){const x=random()*POSTER_SIZE,y=random()*820,r=150+random()*300,g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,alpha(index%2?colors[2]:'#fff',.15));g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);}ctx.save();ctx.globalAlpha=.1;ctx.strokeStyle='#fff';ctx.lineWidth=1;for(let y=0;y<840;y+=36){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(POSTER_SIZE,y+120);ctx.stroke();}ctx.restore();const noise=seeded(seed+919);ctx.save();ctx.globalAlpha=.09;ctx.fillStyle='#fff';for(let index=0;index<1200;index++)ctx.fillRect(noise()*POSTER_SIZE,noise()*POSTER_SIZE,noise()>.82?2:1,1);ctx.restore();}
function drawEyebrow(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,accent:string,dark=false){const label=clean(text)||'FOUNDER.ENV BUSINESS EDIT';ctx.font=`700 22px ${FONT}`;const width=Math.min(620,ctx.measureText(label).width+56);rounded(ctx,x,y,width,52,26,dark?'rgba(4,10,8,.78)':alpha(accent,.2),dark?alpha(accent,.38):alpha('#ffffff',.15));ctx.fillStyle=dark?accent:'#fff';ctx.textBaseline='middle';ctx.fillText(label,x+28,y+27);}
function drawHeroPlaceholder(ctx:CanvasRenderingContext2D,box:Box,accent:string,seed:number,category:string){ctx.save();ctx.beginPath();ctx.roundRect(box.x,box.y,box.width,box.height,54);ctx.clip();const gradient=ctx.createLinearGradient(box.x,box.y,box.x+box.width,box.y+box.height);gradient.addColorStop(0,alpha(accent,.5));gradient.addColorStop(1,'rgba(0,0,0,.18)');ctx.fillStyle=gradient;ctx.fillRect(box.x,box.y,box.width,box.height);const random=seeded(seed);ctx.strokeStyle=alpha('#ffffff',.25);ctx.lineWidth=6;for(let index=0;index<8;index++){const size=70+random()*170,x=box.x+random()*box.width,y=box.y+random()*box.height;ctx.beginPath();ctx.arc(x,y,size,0,Math.PI*2);ctx.stroke();}ctx.fillStyle='rgba(255,255,255,.88)';ctx.font=`800 24px ${FONT}`;ctx.textAlign='center';ctx.fillText(clean(category).toLocaleUpperCase()||'LOCAL BUSINESS',box.x+box.width/2,box.y+box.height/2);ctx.restore();ctx.textAlign='left';}
function drawHero(ctx:CanvasRenderingContext2D,image:HTMLImageElement|null,box:Box,accent:string,seed:number,category:string){ctx.save();ctx.shadowColor='rgba(0,0,0,.35)';ctx.shadowBlur=45;ctx.shadowOffsetY=18;rounded(ctx,box.x,box.y,box.width,box.height,54,'rgba(255,255,255,.08)',alpha('#ffffff',.18));ctx.restore();if(!image)return drawHeroPlaceholder(ctx,box,accent,seed,category);ctx.save();ctx.beginPath();ctx.roundRect(box.x,box.y,box.width,box.height,54);ctx.clip();drawCover(ctx,image,box);const overlay=ctx.createLinearGradient(box.x,box.y,box.x,box.y+box.height);overlay.addColorStop(0,'rgba(0,0,0,.02)');overlay.addColorStop(1,'rgba(0,0,0,.48)');ctx.fillStyle=overlay;ctx.fillRect(box.x,box.y,box.width,box.height);ctx.restore();}

function offerLayout(ctx:CanvasRenderingContext2D,data:RendererData,accent:string,seed:number){drawEyebrow(ctx,data.eyebrow||'LIMITED-TIME OFFER',72,78,accent);drawText(ctx,data.headline,{x:72,y:172,width:430,height:285},{maxSize:74,minSize:46,weight:850,lineHeight:.98,maxLines:4});drawText(ctx,data.supportingText,{x:76,y:478,width:430,height:125},{maxSize:29,minSize:21,weight:500,lineHeight:1.28,maxLines:4,color:'rgba(255,255,255,.8)'});const offer=clean(data.offer)||'SPECIAL VALUE';ctx.save();ctx.translate(770,315);ctx.rotate((seed%2?1:-1)*-.045);ctx.shadowColor='rgba(0,0,0,.32)';ctx.shadowBlur=48;ctx.shadowOffsetY=22;rounded(ctx,-250,-150,500,350,48,'#fff');ctx.shadowColor='transparent';ctx.fillStyle=accent;ctx.font=`800 20px ${FONT}`;ctx.fillText('TODAY’S HIGHLIGHT',-198,-92);drawText(ctx,offer,{x:-198,y:-48,width:396,height:205},{maxSize:62,minSize:28,weight:900,lineHeight:.98,maxLines:4,color:'#07110d'});ctx.restore();cta(ctx,data.cta,74,664,accent);}
function productLayout(ctx:CanvasRenderingContext2D,data:RendererData,accent:string,seed:number,hero:HTMLImageElement|null){const right=seed%2===0;const imageBox={x:right?610:58,y:74,width:412,height:670};drawHero(ctx,hero,imageBox,accent,seed,data.category||'');const x=right?72:548;drawEyebrow(ctx,data.eyebrow||'FEATURED FOR YOU',x,102,accent);drawText(ctx,data.headline,{x,y:205,width:455,height:300},{maxSize:78,minSize:48,weight:850,lineHeight:1,maxLines:4});drawText(ctx,data.supportingText,{x,y:535,width:450,height:125},{maxSize:30,minSize:22,weight:500,lineHeight:1.3,maxLines:4,color:'rgba(255,255,255,.78)'});cta(ctx,data.cta,x,690,accent);}
function festivalLayout(ctx:CanvasRenderingContext2D,data:RendererData,accent:string,seed:number){ctx.save();ctx.translate(540,390);ctx.strokeStyle=alpha(accent,.34);for(let ring=0;ring<4;ring++){ctx.lineWidth=ring===0?3:1;for(let index=0;index<20;index++){ctx.rotate(Math.PI/10);ctx.beginPath();ctx.moveTo(0,90+ring*50);ctx.quadraticCurveTo(42,126+ring*58,0,164+ring*58);ctx.stroke();}}ctx.restore();drawEyebrow(ctx,data.eyebrow||'CELEBRATE WITH US',350,72,accent);drawText(ctx,data.headline,{x:120,y:258,width:840,height:225},{maxSize:84,minSize:54,weight:850,lineHeight:1,maxLines:3,align:'center'});drawText(ctx,data.supportingText,{x:205,y:525,width:670,height:105},{maxSize:30,minSize:22,weight:500,lineHeight:1.3,maxLines:3,align:'center',color:'rgba(255,255,255,.8)'});const line=ctx.createLinearGradient(310,0,770,0);line.addColorStop(0,'rgba(255,255,255,0)');line.addColorStop(.5,accent);line.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=line;ctx.fillRect(310,674,460,2);cta(ctx,data.cta,352,713,accent);void seed;}
function dailyLayout(ctx:CanvasRenderingContext2D,data:RendererData,accent:string,seed:number,hero:HTMLImageElement|null){const imageBox={x:615,y:76,width:407,height:520};drawHero(ctx,hero,imageBox,accent,seed,data.category||'');drawEyebrow(ctx,data.eyebrow||'TODAY’S BUSINESS EDIT',70,76,accent);drawText(ctx,data.headline,{x:70,y:190,width:500,height:315},{maxSize:82,minSize:50,weight:850,lineHeight:.98,maxLines:4});rounded(ctx,70,535,500,160,34,'rgba(4,12,9,.48)',alpha('#ffffff',.12));drawText(ctx,data.supportingText,{x:102,y:568,width:436,height:100},{maxSize:29,minSize:22,weight:520,lineHeight:1.28,maxLines:3,color:'rgba(255,255,255,.82)'});ctx.save();ctx.globalAlpha=.1;ctx.fillStyle='#fff';ctx.font=`900 126px ${FONT}`;ctx.textAlign='right';ctx.fillText(clean(data.dateLabel).split(',')[0].toLocaleUpperCase(),1015,730);ctx.restore();cta(ctx,data.cta,70,733,accent);}
function announcementLayout(ctx:CanvasRenderingContext2D,data:RendererData,accent:string,seed:number){ctx.save();ctx.translate(540,395);ctx.rotate(seed%2?-.035:.035);ctx.shadowColor='rgba(0,0,0,.3)';ctx.shadowBlur=50;rounded(ctx,-462,-264,924,550,52,'rgba(3,10,8,.7)',alpha('#ffffff',.18));ctx.restore();drawEyebrow(ctx,data.eyebrow||'BUSINESS UPDATE',92,95,accent);drawText(ctx,data.headline,{x:92,y:220,width:895,height:240},{maxSize:88,minSize:54,weight:900,lineHeight:.98,maxLines:3});ctx.fillStyle=accent;ctx.fillRect(94,500,132,8);drawText(ctx,data.supportingText,{x:94,y:542,width:810,height:112},{maxSize:31,minSize:23,weight:500,lineHeight:1.28,maxLines:3,color:'rgba(255,255,255,.8)'});cta(ctx,data.cta,94,708,accent);}
function cta(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,accent:string){const label=clean(text)||'Visit us today';ctx.font=`750 25px ${FONT}`;const width=Math.min(490,ctx.measureText(label).width+76);rounded(ctx,x,y,width,68,20,accent);ctx.fillStyle='#07110d';ctx.textBaseline='middle';ctx.fillText(label,x+32,y+35);ctx.fillText('→',x+width-42,y+34);ctx.textBaseline='alphabetic';}

function identityFooter(ctx:CanvasRenderingContext2D,data:RendererData,logo:HTMLImageElement|null,accent:string){const x=50,y=846,width=980,height=184;rounded(ctx,x,y,width,height,38,'rgba(2,8,6,.84)',alpha('#ffffff',.16));if(logo){ctx.save();ctx.beginPath();ctx.roundRect(76,874,116,116,26);ctx.clip();ctx.fillStyle='#fff';ctx.fillRect(76,874,116,116);drawContain(ctx,logo,{x:82,y:880,width:104,height:104});ctx.restore();}else{rounded(ctx,76,874,116,116,26,alpha(accent,.22),alpha(accent,.42));ctx.fillStyle='#fff';ctx.font=`850 42px ${FONT}`;ctx.textAlign='center';ctx.textBaseline='middle';const initials=clean(data.businessName).split(/\s+/).slice(0,2).map(part=>[...part][0]||'').join('').toLocaleUpperCase();ctx.fillText(initials||'FE',134,934);ctx.textAlign='left';ctx.textBaseline='alphabetic';}drawText(ctx,data.businessName,{x:218,y:873,width:400,height:58},{maxSize:38,minSize:24,weight:820,lineHeight:1.04,maxLines:2});const location=clean(data.location),address=clean(data.address),locationText=address&&address.toLowerCase()!==location.toLowerCase()?address:location;drawText(ctx,locationText,{x:218,y:940,width:410,height:66},{maxSize:19,minSize:14,weight:500,lineHeight:1.16,maxLines:3,color:'rgba(255,255,255,.66)'});const contacts=[clean(data.whatsapp||data.phone),clean(data.website||data.instagram)].filter(Boolean);contacts.forEach((value,index)=>{const label=index===0?(data.whatsapp?'WHATSAPP':'CALL'):(data.website?'WEB':'INSTAGRAM');ctx.fillStyle=accent;ctx.font=`750 14px ${FONT}`;ctx.fillText(label,660,895+index*56);drawText(ctx,value,{x:660,y:912+index*56,width:328,height:28},{maxSize:21,minSize:16,weight:650,lineHeight:1.1,maxLines:1,color:'#fff'});});ctx.fillStyle='rgba(255,255,255,.3)';ctx.font=`650 12px ${FONT}`;ctx.textAlign='right';ctx.fillText('CREATED WITH FOUNDER.ENV',998,1010);ctx.textAlign='left';}

export async function renderPoster(generation:AIContentGeneration){const canvas=document.createElement('canvas');canvas.width=POSTER_SIZE;canvas.height=POSTER_SIZE;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Poster rendering is unavailable.');const fallback:[string,string,string]=['#061510','#146340','#6be3a5'],colors=generation.creative.colors?.length===3?generation.creative.colors:fallback,seed=hash(`${generation.id}:${generation.prompt}:${generation.generationDate}:${generation.creative.variant||0}`),data=generation.renderer;paintBackground(ctx,colors,seed);const[logo,hero]=await Promise.all([loadImage(data.logoUrl),loadImage(data.heroImageUrl||generation.creative.backgroundUrl||'')]);switch(layoutFor(generation)){case'offer':offerLayout(ctx,data,colors[2],seed);break;case'festival':festivalLayout(ctx,data,colors[2],seed);break;case'announcement':announcementLayout(ctx,data,colors[2],seed);break;case'product':productLayout(ctx,data,colors[2],seed,hero);break;default:dailyLayout(ctx,data,colors[2],seed,hero);}identityFooter(ctx,data,logo,colors[2]);return canvas;}
export async function posterBlob(generation:AIContentGeneration){const canvas=await renderPoster(generation);return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Poster export failed.')),'image/png',1));}
export function posterFilename(generation:AIContentGeneration){const slug=generation.renderer.businessName.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');return `founderenv-${slug||'business'}-${generation.generationDate}.png`;}
