import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, CalendarDays, Check, Copy, Download, History, Image, Loader2, LockKeyhole, MessageCircle, Send, Share2, Sparkles, WandSparkles } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { AIOrb } from '@/components/ai/AIOrb';
import { businessService, ownerService } from '@/services';
import { AIContentService, type AIContentGeneration, type AIContentType } from '@/services/aiContentService';
import { posterBlob, posterFilename, renderPoster } from '@/features/ai-content/posterRenderer';
import type { Business } from '@/types';
import { cn } from '@/utils/format';

const actions:{label:string;type:AIContentType;prompt:string}[]=[
  {label:"Today's Post",type:'today',prompt:'Create something good for today'},
  {label:'Offer',type:'offer',prompt:"Create a premium poster for today's offer"},
  {label:'Festival',type:'festival',prompt:'Create a tasteful festival greeting for my business'},
  {label:'Product / Service',type:'product_service',prompt:'Highlight one of our main products or services'},
  {label:'Announcement',type:'announcement',prompt:'Create a clear business announcement'},
];
const progress=['Understanding your business...','Creating today\'s idea...','Designing your post...','Preparing your poster...'];

export function AIContentStudioPage(){
  const navigate=useNavigate();const[business,setBusiness]=useState<Business|null>(null),[history,setHistory]=useState<AIContentGeneration[]>([]),[selected,setSelected]=useState<AIContentGeneration|null>(null),[prompt,setPrompt]=useState(''),[type,setType]=useState<AIContentType>('custom'),[loading,setLoading]=useState(true),[generating,setGenerating]=useState(false),[progressIndex,setProgressIndex]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState('');const requestRef=useRef('');
  useEffect(()=>{let active=true;void ownerService.getCurrent().then(owner=>businessService.getByOwner(owner.id)).then(async owned=>{const found=owned[0]??null;if(!active)return;setBusiness(found);if(found){const items=await AIContentService.history(found.id);if(active){setHistory(items);setSelected(items[0]??null);}}}).catch(()=>active&&setError('AI Content Studio could not load right now.')).finally(()=>active&&setLoading(false));return()=>{active=false;};},[]);
  useEffect(()=>{if(!generating)return;const timer=window.setInterval(()=>setProgressIndex(value=>(value+1)%progress.length),1100);return()=>window.clearInterval(timer);},[generating]);
  const usedToday=AIContentService.usedToday(history),missingMemory=business&&!business.description&&!business.servicesSummary;
  const choose=(action:typeof actions[number])=>{setType(action.type);setPrompt(action.prompt);setError('');};
  const generate=async()=>{if(!business||generating||usedToday)return;setGenerating(true);setProgressIndex(0);setError('');setNotice('');try{requestRef.current=requestRef.current||crypto.randomUUID();const item=await AIContentService.generate({prompt,type,business,requestId:requestRef.current});setSelected(item);setHistory(items=>[item,...items.filter(value=>value.id!==item.id)]);requestRef.current='';try{const blob=await posterBlob(item);await AIContentService.attachPoster(item,blob);}catch(cause){console.warn('Poster history upload failed',cause);}setNotice('Your post is ready. Today\'s free generation has been used.');}catch(cause){const message=cause instanceof Error?cause.message:'We could not create your post right now.';setError(message.includes('daily')||message.includes("today's")?"You've created today's free post.":message);}finally{setGenerating(false);}};
  if(loading)return <div className="mx-auto grid min-h-[60vh] place-items-center"><AIOrb/><span className="sr-only">Loading AI Content Studio</span></div>;
  if(!business)return <div className="mx-auto max-w-xl py-16 text-center"><AIOrb/><h1 className="mt-8 text-2xl font-bold">Complete your business profile first</h1><p className="mt-2 text-gray-500">AI Content Studio needs a business name and category to create useful content.</p><Link to="/business/onboarding" className="btn-primary mt-6">Complete profile</Link></div>;
  return <div className="ai-studio mx-auto min-h-[calc(100vh-5rem)] max-w-6xl overflow-hidden rounded-[2rem] bg-[#06100c] text-white shadow-2xl">
    <header className="relative overflow-hidden border-b border-white/10 px-5 py-7 sm:px-9"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_75%_15%,rgba(65,204,139,.2),transparent_35%)]"/><div className="relative flex items-center justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.22em] text-brand-300"><Sparkles size={14}/>Founder.env intelligence</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">AI Content Studio</h1></div><AIOrb compact/></div></header>
    <main className="grid gap-0 lg:grid-cols-[minmax(0,1fr)_340px]">
      <section className="min-w-0 p-5 sm:p-9">
        {selected&&!generating?<Result generation={selected} notice={notice} onBack={()=>setSelected(null)} onCreateMore={()=>navigate('/owner/content-pro')}/>:<>
          <div className="mx-auto flex max-w-2xl flex-col items-center py-8 text-center sm:py-12"><AIOrb/><h2 className="mt-8 text-3xl font-bold tracking-tight sm:text-4xl">{generating?'Creating your post':usedToday?"You've created today's free post.":'Create something for your business'}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-white/55 sm:text-base">{generating?progress[progressIndex]:usedToday?'Come back tomorrow for another free creation, or explore Content Pro.':'Your AI already knows your business. Just tell it what you want to post.'}</p></div>
          {missingMemory&&<Link to="/owner/edit" className="mb-5 block rounded-2xl border border-amber-300/20 bg-amber-300/10 p-4 text-sm text-amber-100">Add a description or your main services for more useful content →</Link>}
          {usedToday?<div className="mx-auto max-w-xl rounded-3xl border border-white/10 bg-white/[.04] p-7 text-center"><LockKeyhole className="mx-auto text-brand-300"/><p className="mt-3 font-semibold">Daily creation complete</p><button onClick={()=>navigate('/owner/content-pro')} className="btn-primary mt-5">Create More</button></div>:<div className="mx-auto max-w-3xl"><div className="flex gap-2 overflow-x-auto pb-3 scrollbar-hide">{actions.map(action=><button key={action.type} onClick={()=>choose(action)} className={cn('shrink-0 rounded-full border px-4 py-2 text-xs font-medium transition',type===action.type?'border-brand-400 bg-brand-400/15 text-brand-200':'border-white/10 bg-white/[.04] text-white/60 hover:border-white/25 hover:text-white')}>{action.label}</button>)}</div><div className="mt-3 rounded-[1.75rem] border border-white/15 bg-white/[.06] p-3 shadow-[0_24px_80px_rgba(0,0,0,.28)] backdrop-blur"><textarea maxLength={600} disabled={generating} value={prompt} onChange={event=>{setPrompt(event.target.value);setType('custom');setError('');}} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void generate();}}} rows={3} placeholder="Create today's post..." className="w-full resize-none bg-transparent px-3 py-2 text-base text-white outline-none placeholder:text-white/30"/><div className="flex items-center justify-between px-2 pb-1"><span className="text-[11px] text-white/30">{prompt.length}/600 · Enter to generate</span><button onClick={()=>void generate()} disabled={!prompt.trim()||generating} className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-500 text-white transition hover:bg-brand-400 disabled:opacity-30" aria-label="Generate content">{generating?<Loader2 className="animate-spin" size={19}/>:<Send size={19}/>}</button></div></div></div>}
          {error&&<p role="alert" className="mx-auto mt-4 max-w-3xl rounded-xl bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}
        </>}
      </section>
      <aside className="border-t border-white/10 bg-black/15 p-5 lg:border-l lg:border-t-0 sm:p-7"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold"><History size={17}/>Previous creations</h2><span className="text-xs text-white/35">{history.length}</span></div><div className="mt-5 space-y-3">{history.length===0?<div className="rounded-2xl border border-dashed border-white/10 p-6 text-center text-sm text-white/35"><Image className="mx-auto mb-2"/>Your creations will appear here.</div>:history.map(item=><button key={item.id} onClick={()=>setSelected(item)} className={cn('w-full rounded-2xl border p-3 text-left transition',selected?.id===item.id?'border-brand-400/50 bg-brand-400/10':'border-white/10 bg-white/[.03] hover:bg-white/[.06]')}><div className="flex items-start gap-3">{item.posterUrl?<img src={item.posterUrl} className="h-16 w-16 rounded-xl object-cover" alt=""/>:<div className="grid h-16 w-16 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-brand-700 to-gray-950"><WandSparkles size={20}/></div>}<div className="min-w-0"><p className="truncate text-sm font-semibold">{item.headline}</p><p className="mt-1 line-clamp-2 text-xs text-white/40">{item.prompt}</p><p className="mt-2 text-[10px] uppercase tracking-wider text-brand-300">{item.generationDate}</p></div></div></button>)}</div></aside>
    </main>
  </div>;
}

function Result({generation,notice,onBack,onCreateMore}:{generation:AIContentGeneration;notice:string;onBack:()=>void;onCreateMore:()=>void}){const[sharing,setSharing]=useState('');const download=async()=>{const blob=await posterBlob(generation),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=posterFilename(generation);anchor.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);};const copy=async()=>{await navigator.clipboard.writeText(generation.caption);setSharing('Caption copied.');};const share=async()=>{const blob=await posterBlob(generation),file=new File([blob],posterFilename(generation),{type:'image/png'});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],text:generation.caption,title:generation.renderer.businessName});setSharing('Shared.');return;}if(navigator.share){await navigator.share({text:generation.caption,title:generation.renderer.businessName});setSharing('Poster attachment is unavailable here. Download it to add manually.');return;}await copy();setSharing('Caption copied. Download the poster to share it.');};const whatsapp=async()=>{await download();await navigator.clipboard.writeText(generation.caption).catch(()=>undefined);window.open(`https://wa.me/?text=${encodeURIComponent(generation.caption)}`,'_blank','noopener,noreferrer');setSharing('Poster downloaded and caption copied. Attach the poster in WhatsApp.');};return <div className="animate-slide-up"><button onClick={onBack} className="mb-5 flex items-center gap-2 text-sm text-white/55 hover:text-white"><ArrowLeft size={16}/>Create another idea</button><div className="grid gap-7 xl:grid-cols-[minmax(300px,520px)_1fr]"><PosterPreview generation={generation}/><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand-300">{generation.type.replace('_',' ')} · {generation.generationDate}</p><h2 className="mt-2 text-2xl font-bold">{generation.headline}</h2><p className="mt-4 whitespace-pre-line rounded-2xl border border-white/10 bg-white/[.04] p-4 text-sm leading-6 text-white/70">{generation.caption}</p>{notice&&<p className="mt-3 flex items-center gap-2 text-xs text-brand-200"><Check size={14}/>{notice}</p>}<div className="mt-5 grid grid-cols-2 gap-2"><Action icon={Download} label="Download" onClick={()=>void download()}/><Action icon={Share2} label="Share" onClick={()=>void share()}/><Action icon={MessageCircle} label="WhatsApp" onClick={()=>void whatsapp()}/><Action icon={Copy} label="Copy Caption" onClick={()=>void copy()}/></div>{sharing&&<p className="mt-3 text-xs text-white/45">{sharing}</p>}<button onClick={onCreateMore} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-brand-400/30 bg-brand-400/10 px-4 py-3 text-sm font-semibold text-brand-200"><LockKeyhole size={16}/>Create More</button></div></div></div>;}
function PosterPreview({generation}:{generation:AIContentGeneration}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{let active=true;void renderPoster(generation).then(canvas=>{if(!active||!ref.current)return;const ctx=ref.current.getContext('2d');ref.current.width=canvas.width;ref.current.height=canvas.height;ctx?.drawImage(canvas,0,0);});return()=>{active=false;};},[generation]);return <canvas ref={ref} className="aspect-square w-full rounded-3xl bg-gray-900 shadow-2xl" aria-label={`Generated poster for ${generation.renderer.businessName}`}/>;}
function Action({icon:Icon,label,onClick}:{icon:typeof Download;label:string;onClick:()=>void}){return <button onClick={onClick} className="flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[.05] px-3 text-sm font-medium transition hover:bg-white/10"><Icon size={16}/>{label}</button>;}

export function ContentProPage(){return <div className="mx-auto max-w-2xl py-16 text-center"><AIOrb/><p className="mt-8 text-xs font-semibold uppercase tracking-[.2em] text-brand-600">Coming soon</p><h1 className="mt-2 text-3xl font-bold">Content Pro</h1><p className="mt-3 text-gray-500">More daily generations, variations, premium formats and a 7-day content planner are being prepared.</p><Link to="/owner/ai-content" className="btn-primary mt-7"><CalendarDays size={17}/>Back to AI Content Studio</Link></div>;}
