import { FormEvent, useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Coins, ReceiptText, Users } from 'lucide-react';
import { founderV2Service, type BenefitSettings, type BillRequest, type FounderBill, type MerchantPaymentAttempt, type MerchantPaymentSettings } from '@/services/v2Service';
import { formatCurrency } from '@/utils/format';
import { useAuth } from '@/auth/AuthProvider';
import { requireSupabase } from '@/lib/supabase';
import { FECoinWallet } from '@/components/rewards/FECoinWallet';
import type { CoinWallet } from '@/services/v2Service';

export function BusinessDashboard() {
  const { ownerBusiness } = useAuth(); const [params,setParams]=useSearchParams();
  const [requests, setRequests] = useState<BillRequest[]>([]); const [bills, setBills] = useState<FounderBill[]>([]); const [selected, setSelected] = useState<BillRequest | null>(null); const [amount, setAmount] = useState(''); const [error, setError] = useState('');
  const [wallet,setWallet]=useState<CoinWallet>({balance:0,earned:0,redeemed:0,transactions:[]});
  const [attempts,setAttempts]=useState<MerchantPaymentAttempt[]>([]),[benefits,setBenefits]=useState<BenefitSettings|null>(null),[merchant,setMerchant]=useState<MerchantPaymentSettings|null>(null);
  const [saving, setSaving] = useState(false); const savingRef = useRef(false);
  const load = () => ownerBusiness?Promise.all([founderV2Service.getOwnerRequests(ownerBusiness.businessId),founderV2Service.getOwnerBills(ownerBusiness.businessId),founderV2Service.getCoinWallet(ownerBusiness.businessId),founderV2Service.getOwnerPaymentAttempts(ownerBusiness.businessId),founderV2Service.getBenefitSettings(ownerBusiness.businessId),founderV2Service.getMerchantSettings(ownerBusiness.businessId)]).then(([r,b,w,a,benefitSettings,merchantSettings])=>{setRequests(r);setBills(b);setWallet(w);setAttempts(a);setBenefits(benefitSettings);setMerchant(merchantSettings);}):Promise.resolve();
  // AuthGate resolves the owner business before mounting this route.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, []);
  useEffect(()=>{const target=params.get('request');if(!target)return;const match=requests.find((item)=>item.id===target);if(match){setSelected(match);setParams({}, {replace:true});}},[params,requests,setParams]);
  // The subscription is keyed only by the stable business id; callbacks read the latest rows.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{if(!ownerBusiness)return;const client=requireSupabase();const filter=`business_id=eq.${ownerBusiness.businessId}`,channel=client.channel(`owner-billing:${ownerBusiness.businessId}`).on('postgres_changes',{event:'*',schema:'public',table:'bill_requests',filter},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'bills',filter},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'merchant_payment_attempts',filter},()=>void load()).subscribe();return()=>{void client.removeChannel(channel);};},[ownerBusiness?.businessId]);
  const submit = async (event: FormEvent) => {
    event.preventDefault();
    if (savingRef.current || !selected || Number(amount) <= 0) return;
    savingRef.current = true;
    setSaving(true);
    setError('');
    try {
      await founderV2Service.createBill(selected.id, { amount: Number(amount) });
      setSelected(null);
      setAmount('');
      await load();
    } catch (caught: unknown) {
      setError(caught instanceof Error ? caught.message : 'Could not create bill.');
    } finally {
      savingRef.current = false;
      setSaving(false);
    }
  };
  const paid = bills.filter((item) => item.paymentStatus === 'paid'); const sales = paid.reduce((sum,item) => sum + item.finalAmount,0);
  return <div className="mx-auto max-w-content pb-10"><p className="text-xs font-semibold uppercase tracking-wider text-brand-600">Business network</p><h1 className="mt-1 text-2xl font-bold">Founder dashboard</h1>{error && <p className="mt-3 rounded-xl bg-error-50 p-3 text-sm text-error-600">{error}</p>}
    <div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric icon={Users} label="Bill requests" value={String(requests.length)} /><Metric icon={ReceiptText} label="Paid bills" value={String(paid.length)} /><Metric icon={Coins} label="Founder sales" value={formatCurrency(sales)} /></div>
    <div className="mt-6"><FECoinWallet wallet={wallet} title="Business FE Coins" /></div>
    <div className="mt-6 grid gap-5 lg:grid-cols-2"><BenefitSettingsCard value={benefits} businessId={ownerBusiness?.businessId||''} onSaved={setBenefits}/><MerchantSettingsCard value={merchant} businessId={ownerBusiness?.businessId||''} onSaved={setMerchant}/></div>
    <section className="card mt-6 p-5"><h2 className="font-semibold">Payment confirmation requests</h2><p className="text-sm text-gray-500">Confirm only after the matching amount and Founder.env reference appear in your merchant UPI account.</p><div className="mt-4 space-y-3">{attempts.filter(item=>item.status==='awaiting_confirmation').length===0?<p className="text-sm text-gray-500">No payments are awaiting confirmation.</p>:attempts.filter(item=>item.status==='awaiting_confirmation').map(item=><div key={item.id} className="rounded-xl border border-amber-200 p-4 dark:border-amber-900"><p className="font-semibold">{item.customerName}</p><div className="mt-2 grid grid-cols-2 gap-2 text-xs"><span>Original Bill</span><strong>{formatCurrency(item.originalAmount)}</strong><span>Founder Benefit</span><strong>{formatCurrency(item.founderBenefit)}</strong><span>FE Discount</span><strong>{formatCurrency(item.feDiscount)}</strong><span>Expected Received</span><strong>{formatCurrency(item.expectedFinalAmount)}</strong></div><p className="mt-2 text-xs text-gray-500">Reference: {item.reference}</p><div className="mt-3 flex flex-wrap gap-2"><button className="btn-primary text-sm" onClick={()=>void founderV2Service.confirmMerchantPayment(item.id).then(load).catch(caught=>setError(caught instanceof Error?caught.message:'Confirmation failed'))}>Confirm {formatCurrency(item.expectedFinalAmount)} Received</button><button className="btn-outline text-sm" onClick={()=>void founderV2Service.rejectMerchantPayment(item.id).then(load).catch(caught=>setError(caught instanceof Error?caught.message:'Update failed'))}>Payment Not Received</button></div></div>)}</div></section>
    <section className="card mt-6 p-5"><h2 className="font-semibold">Bill requests</h2><p className="text-sm text-gray-500">Create a bill from a customer request; benefits are calculated by the database.</p><div className="mt-4 space-y-3">{requests.length === 0 ? <p className="text-sm text-gray-500">No pending bill requests.</p> : requests.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border border-gray-100 p-4 dark:border-gray-800"><div><p className="font-medium">Customer request</p><p className="text-xs text-gray-500">{new Date(item.createdAt).toLocaleString()}</p></div><button className="btn-primary text-sm" onClick={() => setSelected(item)}>Add bill</button></div>)}</div></section>
    <section className="card mt-6 p-5"><h2 className="font-semibold">Recent bills</h2><div className="mt-4 space-y-2">{bills.slice(0,8).map((item) => <div key={item.id} className="flex justify-between text-sm"><span>{formatCurrency(item.finalAmount)} · {item.paymentStatus}</span><span className="text-gray-500">Saved {formatCurrency(item.memberDiscount + item.coinDiscount)}</span></div>)}</div></section>
    {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><form onSubmit={submit} className="card w-full max-w-sm p-5"><h2 className="font-semibold">Add bill</h2><label className="mt-4 block text-sm">Amount<input autoFocus className="input mt-1 w-full" min="1" step="0.01" type="number" value={amount} onChange={(e) => setAmount(e.target.value)} /></label><div className="mt-5 flex justify-end gap-2"><button type="button" className="btn-outline" disabled={saving} onClick={() => setSelected(null)}>Cancel</button><button className="btn-primary" disabled={saving || Number(amount) <= 0}>{saving ? 'Creating...' : 'Create bill'}</button></div></form></div>}
  </div>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof Coins; label: string; value: string }) { return <div className="card p-4"><Icon size={18} className="text-brand-600" /><p className="mt-3 text-xl font-bold">{value}</p><p className="text-sm text-gray-500">{label}</p></div>; }
function BenefitSettingsCard({value,businessId,onSaved}:{value:BenefitSettings|null;businessId:string;onSaved:(value:BenefitSettings)=>void}){const[draft,setDraft]=useState<BenefitSettings>(()=>value||{businessId,enabled:true,percentage:5,minimumBill:1000,maximumBenefit:150,redemptionPercent:2,customerEarnRate:.01,businessEarnRate:.005}),[message,setMessage]=useState('');useEffect(()=>{if(value)setDraft(value);},[value]);const field=(key:keyof BenefitSettings,next:string)=>setDraft(current=>({...current,[key]:Number(next)}));const save=async()=>{if([draft.percentage,draft.minimumBill,draft.maximumBenefit,draft.redemptionPercent,draft.customerEarnRate,draft.businessEarnRate].some(item=>item<0)||draft.percentage>100||draft.redemptionPercent>100){setMessage('Enter valid non-negative rates and percentages.');return;}try{const saved=await founderV2Service.saveBenefitSettings({...draft,businessId});onSaved(saved);setMessage('Founder Benefits saved.');}catch(caught){setMessage(caught instanceof Error?caught.message:'Could not save settings.');}};return <section className="card p-5"><h2 className="font-semibold">Founder Benefits / Rewards Settings</h2><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.enabled} onChange={event=>setDraft(current=>({...current,enabled:event.target.checked}))}/>Enable Founder Benefit</label><div className="mt-4 grid grid-cols-2 gap-3"><NumberField label="Benefit %" value={draft.percentage} onChange={value=>field('percentage',value)}/><NumberField label="Minimum Bill ₹" value={draft.minimumBill} onChange={value=>field('minimumBill',value)}/><NumberField label="Maximum Benefit ₹" value={draft.maximumBenefit} onChange={value=>field('maximumBenefit',value)}/><NumberField label="Maximum FE Redemption %" value={draft.redemptionPercent} onChange={value=>field('redemptionPercent',value)}/><NumberField label="Customer FE per ₹1" value={draft.customerEarnRate} step="0.001" onChange={value=>field('customerEarnRate',value)}/><NumberField label="Business FE per ₹1" value={draft.businessEarnRate} step="0.001" onChange={value=>field('businessEarnRate',value)}/></div><button onClick={()=>void save()} className="btn-primary mt-4">Save Benefits</button>{message&&<p className="mt-2 text-xs text-gray-500">{message}</p>}</section>;}
function MerchantSettingsCard({value,businessId,onSaved}:{value:MerchantPaymentSettings|null;businessId:string;onSaved:(value:MerchantPaymentSettings)=>void}){const[upi,setUpi]=useState(value?.merchantUpi||''),[name,setName]=useState(value?.payeeName||''),[message,setMessage]=useState('');useEffect(()=>{setUpi(value?.merchantUpi||'');setName(value?.payeeName||'');},[value]);const save=async()=>{if(!/^[a-z0-9._-]{2,256}@[a-z0-9.-]{2,64}$/i.test(upi)||name.trim().length<2){setMessage('Enter a valid Merchant UPI ID and payee name.');return;}try{const saved=await founderV2Service.saveMerchantSettings({businessId,merchantUpi:upi,payeeName:name,enabled:true});onSaved(saved);setMessage('UPI payment details saved.');}catch(caught){setMessage(caught instanceof Error?caught.message:'Could not save UPI details.');}};return <section className="card p-5"><h2 className="font-semibold">Payment Settings</h2><p className="mt-1 text-sm text-gray-500">Customer payments go directly to this merchant UPI account.</p><label className="mt-4 block text-sm">Merchant UPI ID / VPA<input className="input mt-1 w-full" value={upi} onChange={event=>setUpi(event.target.value)} placeholder="rahuldresses@upi"/></label><label className="mt-3 block text-sm">Payee / Business Name<input className="input mt-1 w-full" value={name} onChange={event=>setName(event.target.value)} placeholder="Rahul Dresses"/></label><p className="mt-2 text-xs text-gray-400">Founder.env never asks for your UPI PIN, OTP, bank password, or card credentials.</p><button onClick={()=>void save()} className="btn-primary mt-4">{value?'Edit UPI Details':'Add UPI Details'}</button>{!value&&<p className="mt-2 text-xs text-amber-600">Add UPI Details to accept Founder.env bill payments.</p>}{message&&<p className="mt-2 text-xs text-gray-500">{message}</p>}</section>;}
function NumberField({label,value,onChange,step='0.01'}:{label:string;value:number;onChange:(value:string)=>void;step?:string}){return <label className="text-xs text-gray-500">{label}<input className="input mt-1 w-full" min="0" step={step} type="number" value={value} onChange={event=>onChange(event.target.value)}/></label>;}
