import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const migration=readFileSync(new URL('../supabase/migrations/20260815120000_merchant_payment_reward_loop.sql',import.meta.url),'utf8');
const originalV2=readFileSync(new URL('../supabase/migrations/20260812100000_founder_env_v2_billing_loyalty.sql',import.meta.url),'utf8');
const service=readFileSync(new URL('../src/services/v2Service.ts',import.meta.url),'utf8');
const sheet=readFileSync(new URL('../src/components/billing/BillSheet.tsx',import.meta.url),'utf8');
const dashboard=readFileSync(new URL('../src/pages/owner/BusinessDashboard.tsx',import.meta.url),'utf8');

function calculate(original:number,balance:number){const benefit=original>=1000?Math.min(original*.05,150):0,eligible=Math.min(balance,original*.02,original-benefit);return{benefit,available:balance,eligible,feDiscount:eligible,savings:benefit+eligible,final:original-benefit-eligible};}

test('first ₹2,000 transaction uses merchant-funded defaults and no false FE',()=>{assert.deepEqual(calculate(2000,0),{benefit:100,available:0,eligible:0,feDiscount:0,savings:100,final:1900});assert.match(migration,/customer_reward:=round\(target_bill\.original_amount\*coalesce\(settings\.customer_coin_rate,0\),2\)/);assert.match(migration,/business_reward:=round\(target_bill\.original_amount\*coalesce\(settings\.merchant_coin_rate,0\),2\)/);});
test('second participating business accepts existing 20 FE within its 2 percent cap',()=>{assert.deepEqual(calculate(3000,20),{benefit:150,available:20,eligible:20,feDiscount:20,savings:170,final:2830});assert.match(migration,/coin_amount:=least\(max_coin,customer_account\.balance/);});
test('missing and untouched reward rows receive the pilot defaults',()=>{for(const value of ["member_discount_value set default 5","maximum_discount set default 150","minimum_bill set default 1000","max_fe_coin_redemption_percent set default 2","customer_coin_rate set default 0.01","merchant_coin_rate set default 0.005"])assert.match(migration,new RegExp(value));assert.match(migration,/where status='active' on conflict\(business_id\) do nothing/);});
test('owner supplies only original amount while backend selects exact eligible FE',()=>{assert.match(service,/requested_coin_discount: 0/);assert.match(migration,/coin_amount:=least\(max_coin,customer_account\.balance,greatest\(amount-member_amount,0\)\)/);assert.match(migration,/values\(req\.business_id,req\.customer_id,req\.id,amount,member_amount,coin_amount,amount-member_amount-coin_amount/);});
test('merchant UPI is validated and no sensitive banking credentials are stored',()=>{assert.match(migration,/merchant_upi ~\* '\^\[a-z0-9\._-\]/);assert.match(dashboard,/never asks for your UPI PIN, OTP, bank password, or card credentials/);assert.doesNotMatch(migration,/upi_pin|bank_password|card_number|otp text/i);});
test('server creates immutable payment proof before standard UPI intent opens',()=>{assert.match(migration,/create table public\.merchant_payment_attempts/);assert.match(migration,/'FE-'\|\|upper\(substr\(replace\(target_bill\.id::text/);assert.match(service,/pa:value\.merchantUpi/);assert.match(service,/am:value\.expectedFinalAmount\.toFixed\(2\)/);assert.match(service,/tr:value\.reference/);assert.match(sheet,/markAwaiting\(created\.id\)[\s\S]*window\.location\.href/);});
test('opening UPI never marks paid or awards FE',()=>{const awaiting=migration.match(/create or replace function public\.mark_merchant_payment_awaiting[\s\S]*?end \$\$;/i)?.[0]||'';assert.match(awaiting,/payment_status='processing'/);assert.doesNotMatch(awaiting,/status='paid'|fe_coin_transactions/);assert.match(sheet,/Opening a UPI app does not mark this bill paid/);});
test('owner confirmation verifies ownership and every trusted amount before atomic settlement',()=>{const confirm=migration.match(/create or replace function public\.owner_confirm_merchant_payment[\s\S]*?end \$\$;/i)?.[0]||'';assert.match(confirm,/public\.owns_business\(attempt\.business_id\)/);assert.match(confirm,/target_bill\.business_id<>attempt\.business_id/);assert.match(confirm,/target_bill\.customer_id<>attempt\.customer_id/);assert.match(confirm,/target_bill\.final_amount<>attempt\.expected_final_amount/);assert.match(confirm,/status='verified'/);assert.match(confirm,/payment_status='paid',status='paid'/);});
test('duplicate settlement and rewards are idempotent',()=>{assert.match(migration,/if attempt\.status='verified' then return attempt/);assert.match(originalV2,/unique\(account_id, bill_id, type\)/i);assert.match(migration,/on conflict do nothing/);});
test('redemption locks the live account and concurrent attempts reserve FE',()=>{assert.match(migration,/from public\.fe_coin_accounts where id=account\.id for update/);assert.match(migration,/sum\(fe_discount\)[\s\S]*status in\('initiated','awaiting_confirmation'\)/);assert.match(migration,/customer_account\.balance<target_bill\.fe_coin_discount/);assert.match(migration,/'redeem',-target_bill\.fe_coin_discount/);});
test('not received leaves bill unpaid and awards no FE',()=>{const reject=migration.match(/create or replace function public\.owner_reject_merchant_payment[\s\S]*?end \$\$;/i)?.[0]||'';assert.match(reject,/status='not_received'/);assert.match(reject,/payment_status='pending'/);assert.doesNotMatch(reject,/fe_coin_transactions|status='paid'/);});
test('payment privacy is participant-only and confirmation is owner-only',()=>{assert.match(migration,/customer_id=\(select auth\.uid\(\)\) or public\.owns_business\(business_id\)/);assert.match(migration,/where id=target_attempt_id and status='awaiting_confirmation' and public\.owns_business\(business_id\)/);assert.match(migration,/not public\.owns_business\(attempt\.business_id\)/);});
test('mobile bill and owner confirmation UI expose the complete loop without the Early Access dead end',()=>{for(const label of ['Founder Member Benefit','FE Coins Available','Eligible FE Coins','FE Coin Discount','Total Savings','You Pay','Waiting for merchant confirmation'])assert.match(sheet,new RegExp(label));assert.doesNotMatch(sheet,/Online payments are not configured during Early Access/);assert.match(dashboard,/Confirm \{formatCurrency\(item\.expectedFinalAmount\)\} Received/);assert.match(dashboard,/Payment Not Received/);});
