import { useCallback, useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Coins, ReceiptText, Store } from 'lucide-react';
import { BillSheet } from '@/components/billing/BillSheet';
import { FECoinWallet } from '@/components/rewards/FECoinWallet';
import { founderV2Service, type CoinWallet, type FounderBill } from '@/services/v2Service';
import { formatCurrency } from '@/utils/format';

const emptyWallet:CoinWallet={balance:0,earned:0,redeemed:0,transactions:[]};
export function CustomerDashboard(){const[bills,setBills]=useState<FounderBill[]>([]),[wallet,setWallet]=useState<CoinWallet>(emptyWallet),[openBill,setOpenBill]=useState<FounderBill|null>(null),[error,setError]=useState('');const[params,setParams]=useSearchParams();
  const load=useCallback(async()=>{try{const[nextBills,nextWallet]=await Promise.all([founderV2Service.getMyBills(),founderV2Service.getCoinWallet()]);setBills(nextBills);setWallet(nextWallet);const requested=params.get('bill');if(requested){setOpenBill(nextBills.find((item)=>item.id===requested)??null);setParams({}, {replace:true});}}catch(caught){setError(caught instanceof Error?caught.message:'Could not load your account.');}},[params,setParams]);
  useEffect(()=>{void load();},[load]);useEffect(()=>{const refresh=()=>void load();window.addEventListener('founder:notifications-changed',refresh);return()=>window.removeEventListener('founder:notifications-changed',refresh);},[load]);
  const pending=bills.filter((item)=>item.paymentStatus!=='paid'&&item.status!=='cancelled'),savings=bills.reduce((sum,item)=>sum+item.memberDiscount+item.coinDiscount,0);
  return <div className="mx-auto max-w-content pb-10"><p className="text-xs font-semibold uppercase tracking-wider text-brand-600">Founder.env member</p><h1 className="mt-1 text-2xl font-bold">Your Founder benefits</h1>{error&&<p className="mt-3 rounded-xl bg-error-50 p-3 text-sm text-error-600">{error}</p>}<div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric icon={Coins} label="FE Coins" value={`${wallet.balance.toFixed(2)} FE`}/><Metric icon={ReceiptText} label="Founder savings" value={formatCurrency(savings)}/><Metric icon={Store} label="Pending bills" value={String(pending.length)}/></div>
    <div className="mt-6"><FECoinWallet wallet={wallet}/></div>
    <section className="card mt-6 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Your bills</h2><p className="text-sm text-gray-500">Verified payments earn FE Coins once.</p></div><Link className="btn-outline text-sm" to="/explore">Discover businesses</Link></div><div className="mt-4 space-y-3">{bills.length===0?<p className="text-sm text-gray-500">No bills yet. Follow a business and request your first bill.</p>:bills.map((item)=><button key={item.id} onClick={()=>setOpenBill(item)} className="w-full rounded-xl border border-gray-100 p-4 text-left hover:border-brand-200 dark:border-gray-800"><div className="flex justify-between gap-3"><div><p className="font-semibold">{item.businessName||'Founder.env Business'} · {formatCurrency(item.finalAmount)}</p><p className="text-xs text-gray-500">Original {formatCurrency(item.originalAmount)} · Saved {formatCurrency(item.memberDiscount+item.coinDiscount)}</p></div><span className="text-sm font-medium">{item.paymentStatus==='paid'?'Paid ✓':item.status==='cancelled'?'Cancelled':'View bill'}</span></div></button>)}</div></section>{openBill&&<BillSheet bill={openBill} coinsAvailable={wallet.balance} onClose={()=>setOpenBill(null)}/>}</div>;
}
function Metric({icon:Icon,label,value}:{icon:typeof Coins;label:string;value:string}){return <div className="card p-4"><Icon size={18} className="text-brand-600"/><p className="mt-3 text-xl font-bold">{value}</p><p className="text-sm text-gray-500">{label}</p></div>}
