import { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowLeft, Image as ImageIcon, Loader2, Search, Send } from 'lucide-react';
import { Avatar } from '@/components/ui/Avatar';
import { EmptyState } from '@/components/ui/EmptyState';
import { LoadingSpinner } from '@/components/ui/States';
import { useAuth } from '@/auth/AuthProvider';
import { messageService } from '@/services';
import { useCurrentCustomer } from '@/hooks/useCurrentCustomer';
import { cn, formatTime, timeAgo } from '@/utils/format';
import type { Conversation, Message } from '@/types';

type Contact={id:string;name:string;username:string;avatar:string;kind:'business'|'customer';businessId:string};
const enhancedMessages=messageService as typeof messageService&{searchContacts?:(query:string)=>Promise<Contact[]>;startConversation?:(businessId:string,customerId?:string)=>Promise<Conversation|null>;subscribe:(id:string,customerId:string,callback:(message:Message)=>void)=>()=>void};
const previewMessages=messageService as unknown as {subscribe:(id:string,callback:(message:Message)=>void)=>()=>void};
export function MessagesPage(){const{user,profile}=useAuth(),previewCustomer=useCurrentCustomer(),[params]=useSearchParams();const[conversations,setConversations]=useState<Conversation[]>([]),[selected,setSelected]=useState<Conversation|null>(null),[messages,setMessages]=useState<Message[]>([]),[query,setQuery]=useState(''),[contacts,setContacts]=useState<Contact[]>([]),[text,setText]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');const endRef=useRef<HTMLDivElement>(null),fileRef=useRef<HTMLInputElement>(null);const currentId=user?.id||previewCustomer.id,isOwner=profile?.role==='business_owner';
  const reload=async()=>{try{const list=await messageService.getConversations();setConversations(list);const requested=params.get('conversation');if(requested&&!selected){const found=list.find((item)=>item.id===requested);if(found)void open(found);}}catch(caught){setError(caught instanceof Error?caught.message:'Messages could not be loaded.');}finally{setLoading(false);}};
  // The initial inbox fetch intentionally runs once; subsequent refreshes are explicit.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{void reload();},[]);
  useEffect(()=>{let active=true;if(!query.trim()||!enhancedMessages.searchContacts){setContacts([]);return;}const timer=window.setTimeout(()=>{void enhancedMessages.searchContacts!(query).then((items)=>{if(active)setContacts(items);}).catch((caught:unknown)=>setError(caught instanceof Error?caught.message:'Search failed.'));},200);return()=>{active=false;window.clearTimeout(timer);};},[query]);
  const open=async(conv:Conversation)=>{setSelected(conv);setError('');try{setMessages(await messageService.getMessages(conv.id));await messageService.markRead(conv.id);setTimeout(()=>endRef.current?.scrollIntoView({behavior:'smooth'}),50);}catch(caught){setError(caught instanceof Error?caught.message:'Conversation could not be opened.');}};
  const start=async(contact:Contact)=>{if(!enhancedMessages.startConversation)return;setBusy(true);try{const conv=await enhancedMessages.startConversation(contact.businessId,contact.kind==='customer'?contact.id:undefined);if(conv){setQuery('');setContacts([]);await reload();await open(conv);}}catch(caught){setError(caught instanceof Error?caught.message:'Conversation could not be started.');}finally{setBusy(false);}};
  const send=async()=>{if(!selected||!text.trim()||busy)return;setBusy(true);try{const message=await messageService.sendMessage(selected.id,currentId,isOwner?'owner':'customer',text.trim());setMessages((old)=>old.some((item)=>item.id===message.id)?old:[...old,message]);setText('');}catch(caught){setError(caught instanceof Error?caught.message:'Message could not be sent.');}finally{setBusy(false);}};
  const media=async(file:File)=>{if(!selected)return;setBusy(true);try{const message=await messageService.sendMedia(selected.id,file);setMessages((old)=>old.some((item)=>item.id===message.id)?old:[...old,message]);}catch(caught){setError(caught instanceof Error?caught.message:'Image could not be sent.');}finally{setBusy(false);}};
  useEffect(()=>{if(!selected)return;if(enhancedMessages.searchContacts)return enhancedMessages.subscribe(selected.id,selected.customerId,(message)=>{setMessages((old)=>old.some((item)=>item.id===message.id)?old:[...old,message]);});return previewMessages.subscribe(selected.id,(message)=>setMessages((old)=>old.some((item)=>item.id===message.id)?old:[...old,message]));},[selected]);
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?conversations.filter((item)=>`${item.businessName} ${item.businessUsername} ${item.customerName}`.toLowerCase().includes(q)):conversations;},[conversations,query]);
  if(loading)return <LoadingSpinner size={32} className="py-12"/>;
  if(selected){const title=isOwner?selected.customerName:selected.businessName,avatar=isOwner?selected.customerAvatar:selected.businessLogo;return <div className="mx-auto flex h-[calc(100vh-130px)] min-h-[520px] max-w-2xl flex-col overflow-hidden rounded-2xl bg-white shadow-sm dark:bg-gray-950"><div className="flex items-center gap-3 border-b p-3 dark:border-gray-800"><button onClick={()=>{setSelected(null);void reload();}} className="rounded-lg p-2 hover:bg-gray-100 dark:hover:bg-gray-800" aria-label="Back to conversations"><ArrowLeft size={20}/></button>{!isOwner?<Link to={`/business/${selected.businessUsername}`}><Avatar src={avatar} alt={title} size="md"/></Link>:<Avatar src={avatar} alt={title} size="md"/>}<div><p className="font-semibold">{title}</p><p className="text-xs text-gray-500">{isOwner?'Customer':'Business'}</p></div></div>{error&&<p className="m-3 rounded-xl bg-error-50 p-2 text-sm text-error-600">{error}</p>}<div className="flex-1 space-y-3 overflow-y-auto p-4">{messages.length===0&&<p className="py-10 text-center text-sm text-gray-500">No messages yet. Say hello.</p>}{messages.map((message)=>{const mine=message.senderId===currentId;return <div key={message.id} className={cn('flex',mine?'justify-end':'justify-start')}><div className={cn('max-w-[78%] rounded-2xl px-4 py-2.5 text-sm',mine?'rounded-br-sm bg-brand-600 text-white':'rounded-bl-sm bg-gray-100 dark:bg-gray-800')}>{message.imageUrl&&<img src={message.imageUrl} alt="Message attachment" className="mb-2 max-h-60 rounded-lg"/>}{message.text&&<p>{message.text}</p>}<p className={cn('mt-1 text-[10px]',mine?'text-white/60':'text-gray-400')}>{formatTime(message.createdAt)}</p></div></div>})}<div ref={endRef}/></div><div className="flex items-center gap-2 border-t p-3 dark:border-gray-800"><input ref={fileRef} type="file" className="hidden" accept="image/*" onChange={(event)=>{const file=event.target.files?.[0];if(file)void media(file);event.target.value='';}}/><button onClick={()=>fileRef.current?.click()} disabled={busy} className="rounded-xl p-2 text-gray-400" aria-label="Attach image">{busy?<Loader2 size={20} className="animate-spin"/>:<ImageIcon size={20}/>}</button><input value={text} onChange={(event)=>setText(event.target.value)} onKeyDown={(event)=>{if(event.key==='Enter')void send();}} className="input flex-1" placeholder="Type a message..."/><button onClick={()=>void send()} disabled={busy||!text.trim()} className="rounded-xl p-2.5 text-brand-600 disabled:text-gray-300" aria-label="Send message"><Send size={20}/></button></div></div>}
  return <div className="mx-auto max-w-2xl pb-4"><h1 className="text-2xl font-bold">Messages</h1><p className="mt-1 text-sm text-gray-500">{isOwner?'Talk with followers and existing customers.':'Connect directly with Founder.env businesses.'}</p><div className="relative mt-4"><Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={query} onChange={(event)=>setQuery(event.target.value)} className="input pl-10" placeholder={isOwner?'Search customers...':'Search businesses...'}/></div>{error&&<p className="mt-3 rounded-xl bg-error-50 p-3 text-sm text-error-600">{error}</p>}{query.trim()&&contacts.length>0&&<section className="card mt-3 p-3"><p className="px-2 pb-2 text-xs font-semibold uppercase tracking-wider text-gray-400">Start a conversation</p>{contacts.map((contact)=><button key={`${contact.kind}:${contact.id}`} disabled={busy} onClick={()=>void start(contact)} className="flex w-full items-center gap-3 rounded-xl p-2 text-left hover:bg-gray-50 dark:hover:bg-gray-800"><Avatar src={contact.avatar} alt={contact.name} size="md"/><div><p className="text-sm font-semibold">{contact.name}</p>{contact.username&&<p className="text-xs text-gray-500">@{contact.username}</p>}</div></button>)}</section>}<section className="mt-6"><h2 className="mb-2 text-xs font-semibold uppercase tracking-wider text-gray-400">{isOwner?'Customers':'Businesses'}</h2>{filtered.length?<div className="space-y-1">{filtered.map((conv)=>{const title=isOwner?conv.customerName:conv.businessName,avatar=isOwner?conv.customerAvatar:conv.businessLogo;return <button key={conv.id} onClick={()=>void open(conv)} className="flex w-full items-center gap-3 rounded-xl p-3 text-left hover:bg-gray-50 dark:hover:bg-gray-800"><Avatar src={avatar} alt={title} size="md"/><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><p className="truncate text-sm font-semibold">{title}</p><span className="text-xs text-gray-400">{timeAgo(conv.lastMessageAt)}</span></div><p className="truncate text-sm text-gray-500">{conv.lastMessage}</p></div>{conv.unreadCount>0&&<span className="rounded-full bg-brand-600 px-2 py-0.5 text-xs font-bold text-white">{conv.unreadCount}</span>}</button>})}</div>:<EmptyState icon="MessageCircle" title={isOwner?'No customer messages yet':'No conversations yet'} description={isOwner?'Customer conversations will appear here.':'Search for a business to start a conversation.'}/>}</section></div>;
}
