/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as BuildLogRouteImport } from './routes/build-log'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as BusinessesIndexRouteImport } from './routes/businesses/index'
import { Route as DesignsSlugRouteImport } from './routes/designs/$slug'
import { Route as BusinessesSlugIndexRouteImport } from './routes/businesses/$slug/index'
import { Route as BusinessesSlugCategoryRouteImport } from './routes/businesses/$slug/$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildLogRoute = BuildLogRouteImport.update({
  id: '/build-log',
  path: '/build-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesIndexRoute = BusinessesIndexRouteImport.update({
  id: '/businesses/',
  path: '/businesses/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsSlugRoute = DesignsSlugRouteImport.update({
  id: '/designs/$slug',
  path: '/designs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesSlugIndexRoute = BusinessesSlugIndexRouteImport.update({
  id: '/businesses/$slug/',
  path: '/businesses/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesSlugCategoryRoute = BusinessesSlugCategoryRouteImport.update({
  id: '/businesses/$slug/$category',
  path: '/businesses/$slug/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build-log': typeof BuildLogRoute
  '/projects': typeof ProjectsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/designs/$slug': typeof DesignsSlugRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/businesses/$slug/$category': typeof BusinessesSlugCategoryRoute
  '/businesses/$slug/': typeof BusinessesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build-log': typeof BuildLogRoute
  '/projects': typeof ProjectsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/designs/$slug': typeof DesignsSlugRoute
  '/businesses': typeof BusinessesIndexRoute
  '/businesses/$slug/$category': typeof BusinessesSlugCategoryRoute
  '/businesses/$slug': typeof BusinessesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/build-log': typeof BuildLogRoute
  '/projects': typeof ProjectsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/designs/$slug': typeof DesignsSlugRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/businesses/$slug/$category': typeof BusinessesSlugCategoryRoute
  '/businesses/$slug/': typeof BusinessesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/build-log'
    | '/projects'
    | '/admin'
    | '/admin/login'
    | '/designs/$slug'
    | '/businesses/'
    | '/businesses/$slug/$category'
    | '/businesses/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/build-log'
    | '/projects'
    | '/admin'
    | '/admin/login'
    | '/designs/$slug'
    | '/businesses'
    | '/businesses/$slug/$category'
    | '/businesses/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/build-log'
    | '/projects'
    | '/_authenticated/admin'
    | '/admin/login'
    | '/designs/$slug'
    | '/businesses/'
    | '/businesses/$slug/$category'
    | '/businesses/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BuildLogRoute: typeof BuildLogRoute
  ProjectsRoute: typeof ProjectsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  DesignsSlugRoute: typeof DesignsSlugRoute
  BusinessesIndexRoute: typeof BusinessesIndexRoute
  BusinessesSlugCategoryRoute: typeof BusinessesSlugCategoryRoute
  BusinessesSlugIndexRoute: typeof BusinessesSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-log': {
      id: '/build-log'
      path: '/build-log'
      fullPath: '/build-log'
      preLoaderRoute: typeof BuildLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/': {
      id: '/businesses/'
      path: '/businesses'
      fullPath: '/businesses/'
      preLoaderRoute: typeof BusinessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs/$slug': {
      id: '/designs/$slug'
      path: '/designs/$slug'
      fullPath: '/designs/$slug'
      preLoaderRoute: typeof DesignsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$slug/': {
      id: '/businesses/$slug/'
      path: '/businesses/$slug'
      fullPath: '/businesses/$slug/'
      preLoaderRoute: typeof BusinessesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$slug/$category': {
      id: '/businesses/$slug/$category'
      path: '/businesses/$slug/$category'
      fullPath: '/businesses/$slug/$category'
      preLoaderRoute: typeof BusinessesSlugCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BuildLogRoute: BuildLogRoute,
  ProjectsRoute: ProjectsRoute,
  AdminLoginRoute: AdminLoginRoute,
  DesignsSlugRoute: DesignsSlugRoute,
  BusinessesIndexRoute: BusinessesIndexRoute,
  BusinessesSlugCategoryRoute: BusinessesSlugCategoryRoute,
  BusinessesSlugIndexRoute: BusinessesSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
